package ui.auth;

import com.formdev.flatlaf.extras.FlatSVGIcon;

public class LoginPanel extends javax.swing.JPanel {

    // Stores the currently logged-in user's ID
    public static int loggedInUserId = 1;

    // Stores the currently logged-in username
    public static String loggedInUsername = "Admin";

    // Constructor
    // Runs when the Login Panel is created
    public LoginPanel() {

        // Initializes all UI components from NetBeans Form Editor
        initComponents();

        // Placeholder text shown inside the username field
        txtUsername.putClientProperty("JTextField.placeholderText", "admin or staff");

        // Placeholder text shown inside the password field
        txtPassword.putClientProperty("JTextField.placeholderText", "••••••••");

        // Loads SVG icons for username and password fields
        FlatSVGIcon userIcon = new FlatSVGIcon("icons/user.svg", 16, 16);
        FlatSVGIcon lockIcon = new FlatSVGIcon("icons/lock.svg", 16, 16);

        // Adds icons inside the text fields
        txtUsername.putClientProperty("JTextField.leadingIcon", userIcon);
        txtPassword.putClientProperty("JTextField.leadingIcon", lockIcon);

        // Adds spacing between icon and text
        txtUsername.putClientProperty("JTextField.iconTextGap", 16);
        txtPassword.putClientProperty("JTextField.iconTextGap", 16);

        // Adds left padding inside the text fields
        java.awt.Insets textPadding = new java.awt.Insets(0, 12, 0, 0);

        txtUsername.putClientProperty("JTextField.padding", textPadding);
        txtPassword.putClientProperty("JTextField.padding", textPadding);

        // Creates the system's orange brand color
        java.awt.Color brandOrange = new java.awt.Color(249, 115, 22);

        // Changes border color when text field is focused
        txtUsername.putClientProperty("JComponent.focusColor", brandOrange);
        txtPassword.putClientProperty("JComponent.focusColor", brandOrange);

        // Changes highlighted text color
        txtUsername.setSelectionColor(brandOrange);
        txtPassword.setSelectionColor(brandOrange);

        // Sets the logo icon
        logoLabel.setIcon(
                new FlatSVGIcon("icons/utensils-crossed.svg", 28, 28)
        );
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        leftPanel = new javax.swing.JPanel();
        logoLabel = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        rightPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        loginBtn = new javax.swing.JButton();
        txtPassword = new javax.swing.JPasswordField();

        setPreferredSize(new java.awt.Dimension(1280, 720));
        setLayout(new java.awt.GridLayout(1, 0));

        leftPanel.setBackground(new java.awt.Color(232, 90, 14));
        leftPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(40, 40, 40, 40));

        logoLabel.setMaximumSize(new java.awt.Dimension(28, 28));
        logoLabel.setMinimumSize(new java.awt.Dimension(28, 28));
        logoLabel.setPreferredSize(new java.awt.Dimension(28, 28));

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Georgia", 1, 20)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("WeeFee");

        jLabel6.setFont(new java.awt.Font("Geist Medium", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(252, 232, 221));
        jLabel6.setText("FoodHub Management System");

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Georgia", 1, 30)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("<html>\nSimplify sales, inventory, and daily operations.\n</html>");
        jLabel7.setToolTipText("");

        jLabel8.setFont(new java.awt.Font("Geist Medium", 0, 16)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("<html>\nA desktop management system designed for WeeFee FoodHub to help manage transactions, products, inventory, expenses, and reports more efficiently.\n</html>");

        jLabel9.setFont(new java.awt.Font("Geist Medium", 0, 16)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("<html>• Faster transaction processing <br>• Real-time inventory monitoring <br>• Organized expense tracking <br>• Automated sales reports </html>");

        javax.swing.GroupLayout leftPanelLayout = new javax.swing.GroupLayout(leftPanel);
        leftPanel.setLayout(leftPanelLayout);
        leftPanelLayout.setHorizontalGroup(
            leftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(leftPanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(leftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(leftPanelLayout.createSequentialGroup()
                        .addComponent(logoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(leftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5)))
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 505, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 475, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 405, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        leftPanelLayout.setVerticalGroup(
            leftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(leftPanelLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(leftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(logoLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(leftPanelLayout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(3, 3, 3)
                        .addComponent(jLabel6)))
                .addGap(78, 78, 78)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(226, Short.MAX_VALUE))
        );

        add(leftPanel);

        rightPanel.setBackground(new java.awt.Color(255, 255, 255));
        rightPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(40, 40, 40, 40));

        jLabel1.setFont(new java.awt.Font("Georgia", 1, 24)); // NOI18N
        jLabel1.setText("Welcome Back");

        jLabel2.setFont(new java.awt.Font("Geist", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 102, 102));
        jLabel2.setText("Sign in to your WeeFee account to continue.  ");

        jLabel3.setFont(new java.awt.Font("Geist Medium", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 51));
        jLabel3.setText("Username");
        jLabel3.setPreferredSize(new java.awt.Dimension(300, 35));

        txtUsername.setFont(new java.awt.Font("Geist", 0, 12)); // NOI18N
        txtUsername.setSelectionColor(new java.awt.Color(232, 90, 14));
        txtUsername.addActionListener(this::txtUsernameActionPerformed);

        jLabel4.setFont(new java.awt.Font("Geist Medium", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 51, 51));
        jLabel4.setText("Password");
        jLabel4.setPreferredSize(new java.awt.Dimension(300, 35));

        loginBtn.setBackground(new java.awt.Color(232, 90, 14));
        loginBtn.setFont(new java.awt.Font("Geist SemiBold", 1, 14)); // NOI18N
        loginBtn.setForeground(new java.awt.Color(255, 255, 255));
        loginBtn.setText("Login");
        loginBtn.setPreferredSize(new java.awt.Dimension(72, 40));
        loginBtn.addActionListener(this::loginBtnActionPerformed);

        txtPassword.setFont(new java.awt.Font("Geist", 0, 12)); // NOI18N
        txtPassword.setPreferredSize(new java.awt.Dimension(64, 20));
        txtPassword.setSelectionColor(new java.awt.Color(232, 90, 14));
        txtPassword.addActionListener(this::txtPasswordActionPerformed);

        javax.swing.GroupLayout rightPanelLayout = new javax.swing.GroupLayout(rightPanel);
        rightPanel.setLayout(rightPanelLayout);
        rightPanelLayout.setHorizontalGroup(
            rightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rightPanelLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(rightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addComponent(txtUsername)
                    .addComponent(loginBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 510, Short.MAX_VALUE)
                    .addComponent(txtPassword, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        rightPanelLayout.setVerticalGroup(
            rightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, rightPanelLayout.createSequentialGroup()
                .addContainerGap(188, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(loginBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(150, 150, 150))
        );

        add(rightPanel);
    }// </editor-fold>//GEN-END:initComponents

    private void txtUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsernameActionPerformed

    }//GEN-LAST:event_txtUsernameActionPerformed

    private void loginBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginBtnActionPerformed
        // Gets the entered username
        String username = txtUsername.getText();

        // Gets the entered password
        String password = new String(txtPassword.getPassword());

        // Checks if username or password is empty
        if (username.isEmpty() || password.isEmpty()) {

            // Shows warning message
            javax.swing.JOptionPane.showMessageDialog(
                    this,
                    "Please enter both Username and Password."
            );

            return;
        }

        // Connects to the database
        try (java.sql.Connection conn
                = database.DBConnection.getConnection()) {

            // SQL query to check if username and password exist
            String sql
                    = "SELECT user_id, username, role FROM Users WHERE username = ? AND password = ?";

            // PreparedStatement prevents SQL Injection
            try (java.sql.PreparedStatement pstmt
                    = conn.prepareStatement(sql)) {

                // Replaces first ? with username
                pstmt.setString(1, username);

                // Replaces second ? with password
                pstmt.setString(2, password);

                // Executes the query
                try (java.sql.ResultSet rs = pstmt.executeQuery()) {

                    // Checks if matching account exists
                    if (rs.next()) {

                        // Stores logged-in user's ID
                        loggedInUserId = rs.getInt("user_id");

                        // Stores logged-in username
                        loggedInUsername = rs.getString("username");

                        // Gets user role
                        String userRole
                                = rs.getString("role").trim();

                        // SQL query for Audit Log
                        String logSql
                                = "INSERT INTO AuditLogs (user_id, action, description) VALUES (?, 'USER_LOGIN', ?)";

                        // Saves login activity into AuditLogs table
                        try (java.sql.PreparedStatement logStmt
                                = conn.prepareStatement(logSql)) {

                            // Inserts user ID
                            logStmt.setInt(1, loggedInUserId);

                            // Inserts login description
                            logStmt.setString(
                                    2,
                                    loggedInUsername + " successfully logged into the system."
                            );

                            // Executes insert query
                            logStmt.executeUpdate();
                        }

                        // Opens MainFrame dashboard
                        ui.MainFrame mainApp
                                = new ui.MainFrame(userRole);

                        mainApp.setVisible(true);

                        // Closes Login Window
                        javax.swing.SwingUtilities
                                .getWindowAncestor(this)
                                .dispose();

                    } else {

                        // Runs if username/password is incorrect
                        javax.swing.JOptionPane.showMessageDialog(
                                this,
                                "Invalid Username or Password!",
                                "Login Failed",
                                javax.swing.JOptionPane.ERROR_MESSAGE
                        );
                    }
                }
            }

        } catch (Exception e) {

            // Prints error in console
            e.printStackTrace();

            // Shows database error message
            javax.swing.JOptionPane.showMessageDialog(
                    this,
                    "A system error occurred during login. Please check your connection or contact the administrator.",
                    "System Error",
                    javax.swing.JOptionPane.ERROR_MESSAGE
            );
        }
    }//GEN-LAST:event_loginBtnActionPerformed

    private void txtPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPasswordActionPerformed

    }//GEN-LAST:event_txtPasswordActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel leftPanel;
    private javax.swing.JButton loginBtn;
    private javax.swing.JLabel logoLabel;
    private javax.swing.JPanel rightPanel;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
