package ui;

public class MainFrame extends javax.swing.JFrame {

    // Logger used for debugging or error messages
    private static final java.util.logging.Logger logger
            = java.util.logging.Logger.getLogger(MainFrame.class.getName());

    // Default constructor
    // This runs when the program first starts
    public MainFrame() {

        // Initializes all UI components made in the Form Editor
        initComponents();

        // Gets the CardLayout of the frame
        java.awt.CardLayout cl
                = (java.awt.CardLayout) getContentPane().getLayout();

        // Shows the Login Panel first
        cl.show(getContentPane(), "card2");
    }

    // Constructor with role parameter
    // Used after successful login
    public MainFrame(String role) {

        // Initializes all UI components
        initComponents();

        // Gets the CardLayout
        java.awt.CardLayout cl
                = (java.awt.CardLayout) getContentPane().getLayout();

        // Shows the Dashboard Panel
        cl.show(getContentPane(), "DASHBOARD_CARD");

        // Applies role-based access/security rules
        // Example:
        // Admin = full access
        // Cashier = limited access
        dashboardPanel.applySecurityRules(role);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        loginPanel = new ui.auth.LoginPanel();
        dashboardPanel = new ui.dashboard.DashboardPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("WeeFee FoodHub Management System");
        setPreferredSize(new java.awt.Dimension(1280, 720));
        setResizable(false);
        getContentPane().setLayout(new java.awt.CardLayout());
        getContentPane().add(loginPanel, "card2");
        getContentPane().add(dashboardPanel, "DASHBOARD_CARD");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    /**
     * Main method Starting point of the Java application
     */
    public static void main(String args[]) {

        try {

            // Applies FlatLaf modern UI design
            javax.swing.UIManager.setLookAndFeel(
                    new com.formdev.flatlaf.FlatLightLaf());

            // Makes buttons have rounded corners
            javax.swing.UIManager.put("Button.arc", 15);

            // Makes components have rounded corners
            javax.swing.UIManager.put("Component.arc", 15);

            // Makes text fields have rounded corners
            javax.swing.UIManager.put("TextComponent.arc", 15);

        } catch (Exception ex) {

            // Shows error if FlatLaf fails to load
            System.err.println("Failed to initialize FlatLaf");
        }

        // Runs the UI safely in the Event Dispatch Thread
        java.awt.EventQueue.invokeLater(()
                -> new MainFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private ui.dashboard.DashboardPanel dashboardPanel;
    private ui.auth.LoginPanel loginPanel;
    // End of variables declaration//GEN-END:variables
}
