package ui;

import ui.auth.LoginPanel;

public class MainFrame extends javax.swing.JFrame {
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MainFrame.class.getName());

    public MainFrame() {
        initComponents();
        
        java.awt.CardLayout cl = (java.awt.CardLayout) getContentPane().getLayout();
        cl.show(getContentPane(), "card2"); 
    }

    public MainFrame(String role) {
        initComponents();
        
        java.awt.CardLayout cl = (java.awt.CardLayout) getContentPane().getLayout();
        cl.show(getContentPane(), "DASHBOARD_CARD");
        
        dashboardPanel.applySecurityRules(role);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        loginPanel = new ui.auth.LoginPanel();
        dashboardPanel = new ui.dashboard.DashboardPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("WeeFee FoodHub Management System");
        setPreferredSize(new java.awt.Dimension(1280, 720));
        setResizable(false);
        getContentPane().setLayout(new java.awt.CardLayout());
        getContentPane().add(loginPanel, "card2");
        getContentPane().add(dashboardPanel, "DASHBOARD_CARD");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            javax.swing.UIManager.setLookAndFeel(new com.formdev.flatlaf.FlatLightLaf());
            
            javax.swing.UIManager.put("Button.arc", 15);
            javax.swing.UIManager.put("Component.arc", 15);
            javax.swing.UIManager.put("TextComponent.arc", 15);
            
        } catch (Exception ex) {
            System.err.println("Failed to initialize FlatLaf");
        }
        
        java.awt.EventQueue.invokeLater(() -> new MainFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private ui.dashboard.DashboardPanel dashboardPanel;
    private ui.auth.LoginPanel loginPanel;
    // End of variables declaration//GEN-END:variables
}
