package ui.dashboard;

import ui.menuPanel.ExpensesPanel;
import ui.menuPanel.InventoryPanel;
import ui.menuPanel.POSPanel;
import ui.menuPanel.ProductsPanel;
import ui.menuPanel.PurchasesPanel;
import ui.menuPanel.ReportsPanel;
import ui.menuPanel.SuppliersPanel;
import ui.menuPanel.SystemLogsPanel;
import ui.menuPanel.TransactionsPanel;
import ui.menuPanel.HomePanel;
import ui.auth.LoginPanel;

public class DashboardPanel extends javax.swing.JPanel {

    private HomePanel homeScreen;
    private POSPanel posScreen;
    private InventoryPanel inventoryScreen;
    private ProductsPanel productsScreen;
    private SuppliersPanel suppliersScreen;
    private PurchasesPanel purchasesScreen;
    private ExpensesPanel expensesScreen;
    private ReportsPanel reportsScreen;
    private TransactionsPanel transactionsScreen;
    private SystemLogsPanel logsScreen;
    private java.awt.CardLayout cardLayout;

    public DashboardPanel() {
        this("Admin");
    }

    public DashboardPanel(String userRole) {
        initComponents();
        
        lblUser.setText(LoginPanel.loggedInUsername);

        cardLayout = new java.awt.CardLayout();
        MainCardsPanel.setLayout(cardLayout);

        homeScreen = new HomePanel();
        posScreen = new POSPanel();
        inventoryScreen = new InventoryPanel();
        productsScreen = new ProductsPanel();
        suppliersScreen = new SuppliersPanel();
        purchasesScreen = new PurchasesPanel();
        expensesScreen = new ExpensesPanel();
        reportsScreen = new ReportsPanel();
        transactionsScreen = new TransactionsPanel();
        logsScreen = new SystemLogsPanel();

        MainCardsPanel.add(homeScreen, "CardHome");
        MainCardsPanel.add(posScreen, "CardPOS");
        MainCardsPanel.add(inventoryScreen, "CardInventory");
        MainCardsPanel.add(productsScreen, "CardProducts");
        MainCardsPanel.add(suppliersScreen, "CardSuppliers");
        MainCardsPanel.add(purchasesScreen, "CardPurchases");
        MainCardsPanel.add(expensesScreen, "CardExpenses");
        MainCardsPanel.add(reportsScreen, "CardReports");
        MainCardsPanel.add(transactionsScreen, "CardTransactions");
        MainCardsPanel.add(logsScreen, "CardLogs");

        javax.swing.UIManager.put("Component.focusWidth", 2);
        javax.swing.UIManager.put("Component.innerFocusWidth", 0);
        javax.swing.UIManager.put("Component.focusColor", new java.awt.Color(226, 232, 240));
        javax.swing.UIManager.put("Button.shadowWidth", 2);

        applySecurityRules(userRole);
    }

    private void setActiveNavButton(javax.swing.JButton clickedButton) {
        javax.swing.JButton[] navButtons = {
            btnNavHome, btnNavPOS, btnNavInventory, btnNavProducts, btnNavSuppliers,
            btnNavPurchases, btnNavExpenses, btnNavReports, btnNavTransactions, btnNavAuditLogs
        };

        java.awt.Color brandOrange = new java.awt.Color(227, 83, 10);

        for (javax.swing.JButton btn : navButtons) {
            if (btn != null) {
                btn.setBackground(new java.awt.Color(255, 255, 255));
                btn.setForeground(new java.awt.Color(100, 116, 139));

                btn.putClientProperty("JComponent.outline", null);
            }
        }

        if (clickedButton != null) {
            clickedButton.setBackground(brandOrange);
            clickedButton.setForeground(new java.awt.Color(255, 255, 255));

            clickedButton.setFocusable(true);
            clickedButton.requestFocusInWindow();
        }
    }

    public void applySecurityRules(String role) {
        if (role.equals("Cashier")) {
            btnNavInventory.setVisible(false);
            btnNavProducts.setVisible(false);
            btnNavSuppliers.setVisible(false);
            btnNavPurchases.setVisible(false);
            btnNavExpenses.setVisible(false);
            btnNavReports.setVisible(false);
            btnNavAuditLogs.setVisible(false);

            cardLayout.show(MainCardsPanel, "CardHome");
            setActiveNavButton(btnNavHome);

        } else if (role.equals("Admin")) {
            cardLayout.show(MainCardsPanel, "CardHome");
            setActiveNavButton(btnNavHome);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sidebarPanel = new javax.swing.JPanel();
        btnNavPOS = new javax.swing.JButton();
        btnNavInventory = new javax.swing.JButton();
        btnNavProducts = new javax.swing.JButton();
        btnNavSuppliers = new javax.swing.JButton();
        btnNavAuditLogs = new javax.swing.JButton();
        btnNavLogout = new javax.swing.JButton();
        btnNavTransactions = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        btnNavPurchases = new javax.swing.JButton();
        btnNavExpenses = new javax.swing.JButton();
        btnNavReports = new javax.swing.JButton();
        btnNavHome = new javax.swing.JButton();
        ContentWrapperPanel = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        lblUser = new javax.swing.JLabel();
        MainCardsPanel = new javax.swing.JPanel();

        setMaximumSize(new java.awt.Dimension(1280, 720));
        setPreferredSize(new java.awt.Dimension(1280, 720));
        setLayout(new java.awt.BorderLayout());

        sidebarPanel.setBackground(new java.awt.Color(255, 255, 255));
        sidebarPanel.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 0, 1, new java.awt.Color(226, 232, 240)));
        sidebarPanel.setPreferredSize(new java.awt.Dimension(240, 720));

        btnNavPOS.setFont(new java.awt.Font("Geist", 0, 13)); // NOI18N
        btnNavPOS.setForeground(new java.awt.Color(100, 116, 139));
        btnNavPOS.setText("POS");
        btnNavPOS.setBorderPainted(false);
        btnNavPOS.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnNavPOS.setFocusPainted(false);
        btnNavPOS.setPreferredSize(new java.awt.Dimension(225, 23));
        btnNavPOS.addActionListener(this::btnNavPOSActionPerformed);

        btnNavInventory.setFont(new java.awt.Font("Geist", 0, 13)); // NOI18N
        btnNavInventory.setForeground(new java.awt.Color(100, 116, 139));
        btnNavInventory.setText("Inventory");
        btnNavInventory.setBorderPainted(false);
        btnNavInventory.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnNavInventory.setFocusPainted(false);
        btnNavInventory.setPreferredSize(new java.awt.Dimension(225, 23));
        btnNavInventory.addActionListener(this::btnNavInventoryActionPerformed);

        btnNavProducts.setFont(new java.awt.Font("Geist", 0, 13)); // NOI18N
        btnNavProducts.setForeground(new java.awt.Color(100, 116, 139));
        btnNavProducts.setText("Products");
        btnNavProducts.setBorderPainted(false);
        btnNavProducts.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnNavProducts.setFocusPainted(false);
        btnNavProducts.setPreferredSize(new java.awt.Dimension(225, 23));
        btnNavProducts.addActionListener(this::btnNavProductsActionPerformed);

        btnNavSuppliers.setFont(new java.awt.Font("Geist", 0, 13)); // NOI18N
        btnNavSuppliers.setForeground(new java.awt.Color(100, 116, 139));
        btnNavSuppliers.setText("Suppliers");
        btnNavSuppliers.setBorderPainted(false);
        btnNavSuppliers.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnNavSuppliers.setFocusPainted(false);
        btnNavSuppliers.setPreferredSize(new java.awt.Dimension(225, 23));
        btnNavSuppliers.addActionListener(this::btnNavSuppliersActionPerformed);

        btnNavAuditLogs.setFont(new java.awt.Font("Geist", 0, 13)); // NOI18N
        btnNavAuditLogs.setForeground(new java.awt.Color(100, 116, 139));
        btnNavAuditLogs.setText("System Logs");
        btnNavAuditLogs.setBorderPainted(false);
        btnNavAuditLogs.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnNavAuditLogs.setFocusPainted(false);
        btnNavAuditLogs.setPreferredSize(new java.awt.Dimension(225, 23));
        btnNavAuditLogs.addActionListener(this::btnNavAuditLogsActionPerformed);

        btnNavLogout.setFont(new java.awt.Font("Geist", 1, 14)); // NOI18N
        btnNavLogout.setForeground(new java.awt.Color(100, 116, 139));
        btnNavLogout.setText("Logout");
        btnNavLogout.setBorderPainted(false);
        btnNavLogout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnNavLogout.setFocusPainted(false);
        btnNavLogout.setPreferredSize(new java.awt.Dimension(225, 23));
        btnNavLogout.addActionListener(this::btnNavLogoutActionPerformed);

        btnNavTransactions.setFont(new java.awt.Font("Geist", 0, 13)); // NOI18N
        btnNavTransactions.setForeground(new java.awt.Color(100, 116, 139));
        btnNavTransactions.setText("Transactions");
        btnNavTransactions.setBorderPainted(false);
        btnNavTransactions.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnNavTransactions.setFocusPainted(false);
        btnNavTransactions.setPreferredSize(new java.awt.Dimension(225, 23));
        btnNavTransactions.addActionListener(this::btnNavTransactionsActionPerformed);

        jLabel3.setFont(new java.awt.Font("Geist SemiBold", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 102, 102));
        jLabel3.setText("MAIN MENU");

        btnNavPurchases.setFont(new java.awt.Font("Geist", 0, 13)); // NOI18N
        btnNavPurchases.setForeground(new java.awt.Color(100, 116, 139));
        btnNavPurchases.setText("Purchases");
        btnNavPurchases.setBorderPainted(false);
        btnNavPurchases.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnNavPurchases.setFocusPainted(false);
        btnNavPurchases.setPreferredSize(new java.awt.Dimension(225, 23));
        btnNavPurchases.addActionListener(this::btnNavPurchasesActionPerformed);

        btnNavExpenses.setFont(new java.awt.Font("Geist", 0, 13)); // NOI18N
        btnNavExpenses.setForeground(new java.awt.Color(100, 116, 139));
        btnNavExpenses.setText("Expenses");
        btnNavExpenses.setBorderPainted(false);
        btnNavExpenses.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnNavExpenses.setFocusPainted(false);
        btnNavExpenses.setPreferredSize(new java.awt.Dimension(225, 23));
        btnNavExpenses.addActionListener(this::btnNavExpensesActionPerformed);

        btnNavReports.setFont(new java.awt.Font("Geist", 0, 13)); // NOI18N
        btnNavReports.setForeground(new java.awt.Color(100, 116, 139));
        btnNavReports.setText("Reports");
        btnNavReports.setBorderPainted(false);
        btnNavReports.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnNavReports.setFocusPainted(false);
        btnNavReports.setPreferredSize(new java.awt.Dimension(225, 23));
        btnNavReports.addActionListener(this::btnNavReportsActionPerformed);

        btnNavHome.setFont(new java.awt.Font("Geist", 0, 13)); // NOI18N
        btnNavHome.setForeground(new java.awt.Color(100, 116, 139));
        btnNavHome.setText("Home");
        btnNavHome.setBorderPainted(false);
        btnNavHome.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnNavHome.setFocusPainted(false);
        btnNavHome.setPreferredSize(new java.awt.Dimension(225, 23));
        btnNavHome.addActionListener(this::btnNavHomeActionPerformed);

        javax.swing.GroupLayout sidebarPanelLayout = new javax.swing.GroupLayout(sidebarPanel);
        sidebarPanel.setLayout(sidebarPanelLayout);
        sidebarPanelLayout.setHorizontalGroup(
            sidebarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sidebarPanelLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(sidebarPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(sidebarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnNavPOS, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnNavInventory, javax.swing.GroupLayout.DEFAULT_SIZE, 227, Short.MAX_VALUE)
                    .addComponent(btnNavProducts, javax.swing.GroupLayout.DEFAULT_SIZE, 227, Short.MAX_VALUE)
                    .addComponent(btnNavSuppliers, javax.swing.GroupLayout.DEFAULT_SIZE, 227, Short.MAX_VALUE)
                    .addComponent(btnNavAuditLogs, javax.swing.GroupLayout.DEFAULT_SIZE, 227, Short.MAX_VALUE)
                    .addComponent(btnNavLogout, javax.swing.GroupLayout.DEFAULT_SIZE, 227, Short.MAX_VALUE)
                    .addComponent(btnNavTransactions, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnNavPurchases, javax.swing.GroupLayout.DEFAULT_SIZE, 227, Short.MAX_VALUE)
                    .addComponent(btnNavExpenses, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 227, Short.MAX_VALUE)
                    .addComponent(btnNavReports, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 227, Short.MAX_VALUE)
                    .addComponent(btnNavHome, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        sidebarPanelLayout.setVerticalGroup(
            sidebarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sidebarPanelLayout.createSequentialGroup()
                .addGap(97, 97, 97)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnNavHome, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnNavPOS, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnNavTransactions, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnNavInventory, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnNavProducts, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnNavSuppliers, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnNavPurchases, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnNavExpenses, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnNavReports, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnNavAuditLogs, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 123, Short.MAX_VALUE)
                .addComponent(btnNavLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );

        add(sidebarPanel, java.awt.BorderLayout.LINE_START);

        ContentWrapperPanel.setBackground(new java.awt.Color(248, 250, 252));
        ContentWrapperPanel.setLayout(new java.awt.BorderLayout());

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(226, 232, 240)));
        jPanel3.setPreferredSize(new java.awt.Dimension(1040, 60));

        jLabel4.setFont(new java.awt.Font("Geist Medium", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 102, 102));
        jLabel4.setText("Welcome");

        lblUser.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        lblUser.setForeground(new java.awt.Color(15, 23, 42));
        lblUser.setText("User");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(lblUser, javax.swing.GroupLayout.PREFERRED_SIZE, 603, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(417, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(lblUser, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        ContentWrapperPanel.add(jPanel3, java.awt.BorderLayout.PAGE_START);

        MainCardsPanel.setBackground(new java.awt.Color(248, 250, 252));
        MainCardsPanel.setLayout(new java.awt.CardLayout());
        ContentWrapperPanel.add(MainCardsPanel, java.awt.BorderLayout.CENTER);

        add(ContentWrapperPanel, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void btnNavAuditLogsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNavAuditLogsActionPerformed
        logsScreen.loadLogs("");
        cardLayout.show(MainCardsPanel, "CardLogs");
        setActiveNavButton(btnNavAuditLogs);
    }//GEN-LAST:event_btnNavAuditLogsActionPerformed

    private void btnNavLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNavLogoutActionPerformed
        int confirm = javax.swing.JOptionPane.showConfirmDialog(this,
                "Are you sure you want to log out of the system?",
                "Confirm Logout",
                javax.swing.JOptionPane.YES_NO_OPTION,
                javax.swing.JOptionPane.QUESTION_MESSAGE);

        if (confirm == javax.swing.JOptionPane.YES_OPTION) {

            LoginPanel.loggedInUserId = 0;
            LoginPanel.loggedInUsername = "";

            java.awt.Window currentWindow = javax.swing.SwingUtilities.getWindowAncestor(this);
            if (currentWindow != null) {
                currentWindow.dispose();
            }

            java.awt.EventQueue.invokeLater(() -> {
                javax.swing.JFrame loginFrame = new javax.swing.JFrame("WeeFee FoodHub - Login");
                loginFrame.setDefaultCloseOperation(javax.swing.JFrame.EXIT_ON_CLOSE);
                loginFrame.getContentPane().add(new ui.auth.LoginPanel());
                loginFrame.pack();
                loginFrame.setLocationRelativeTo(null);
                loginFrame.setVisible(true);
            });
        }
    }//GEN-LAST:event_btnNavLogoutActionPerformed

    private void btnNavPOSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNavPOSActionPerformed
        posScreen.loadMenuCards("", "All");
        cardLayout.show(MainCardsPanel, "CardPOS");
        setActiveNavButton(btnNavPOS);
    }//GEN-LAST:event_btnNavPOSActionPerformed

    private void btnNavInventoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNavInventoryActionPerformed
        inventoryScreen.loadInventoryToTable();
        cardLayout.show(MainCardsPanel, "CardInventory");
        setActiveNavButton(btnNavInventory);
    }//GEN-LAST:event_btnNavInventoryActionPerformed

    private void btnNavProductsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNavProductsActionPerformed
        productsScreen.loadProducts("");
        cardLayout.show(MainCardsPanel, "CardProducts");
        setActiveNavButton(btnNavProducts);
    }//GEN-LAST:event_btnNavProductsActionPerformed

    private void btnNavSuppliersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNavSuppliersActionPerformed
        cardLayout.show(MainCardsPanel, "CardSuppliers");
        setActiveNavButton(btnNavSuppliers);
    }//GEN-LAST:event_btnNavSuppliersActionPerformed

    private void btnNavTransactionsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNavTransactionsActionPerformed
        transactionsScreen.loadTransactions("");
        cardLayout.show(MainCardsPanel, "CardTransactions");
        setActiveNavButton(btnNavTransactions);
    }//GEN-LAST:event_btnNavTransactionsActionPerformed

    private void btnNavPurchasesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNavPurchasesActionPerformed
        purchasesScreen.loadPurchases();
        cardLayout.show(MainCardsPanel, "CardPurchases");
        setActiveNavButton(btnNavPurchases);
    }//GEN-LAST:event_btnNavPurchasesActionPerformed

    private void btnNavExpensesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNavExpensesActionPerformed
        cardLayout.show(MainCardsPanel, "CardExpenses");
        setActiveNavButton(btnNavExpenses);
    }//GEN-LAST:event_btnNavExpensesActionPerformed

    private void btnNavReportsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNavReportsActionPerformed
        cardLayout.show(MainCardsPanel, "CardReports");
        setActiveNavButton(btnNavReports);
    }//GEN-LAST:event_btnNavReportsActionPerformed

    private void btnNavHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNavHomeActionPerformed
        homeScreen.loadDashboardData();
        cardLayout.show(MainCardsPanel, "CardHome");
        setActiveNavButton(btnNavHome);
    }//GEN-LAST:event_btnNavHomeActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ContentWrapperPanel;
    private javax.swing.JPanel MainCardsPanel;
    private javax.swing.JButton btnNavAuditLogs;
    private javax.swing.JButton btnNavExpenses;
    private javax.swing.JButton btnNavHome;
    private javax.swing.JButton btnNavInventory;
    private javax.swing.JButton btnNavLogout;
    private javax.swing.JButton btnNavPOS;
    private javax.swing.JButton btnNavProducts;
    private javax.swing.JButton btnNavPurchases;
    private javax.swing.JButton btnNavReports;
    private javax.swing.JButton btnNavSuppliers;
    private javax.swing.JButton btnNavTransactions;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lblUser;
    private javax.swing.JPanel sidebarPanel;
    // End of variables declaration//GEN-END:variables
}
