package ui.dialogs;

// Imports JOptionPane for popup messages
import javax.swing.JOptionPane;

public class AddPurchaseDialog extends javax.swing.JDialog {

    // Logger used for debugging or tracking errors
    private static final java.util.logging.Logger logger
            = java.util.logging.Logger.getLogger(
                    AddPurchaseDialog.class.getName()
            );

    // Constructor
    // Creates the dialog window
    public AddPurchaseDialog(java.awt.Frame parent, boolean modal) {

        // Calls parent constructor
        super(parent, modal);

        // Initializes all UI components
        initComponents();

        // Loads suppliers and products into combo boxes
        loadDropdowns();
    }

    // Loads supplier and product data from database
    private void loadDropdowns() {

        // Clears existing items
        cbSupplier.removeAllItems();
        cbProduct.removeAllItems();

        try {

            // Connects to database
            java.sql.Connection conn
                    = database.DBConnection.getConnection();

            // Gets all active suppliers
            java.sql.ResultSet rsSuppliers
                    = conn.createStatement().executeQuery(
                            "SELECT supplier_id, supplier_name "
                            + "FROM Suppliers "
                            + "WHERE is_archived = 0"
                    );

            // Adds suppliers into combo box
            while (rsSuppliers.next()) {

                cbSupplier.addItem(
                        rsSuppliers.getInt("supplier_id")
                        + " - "
                        + rsSuppliers.getString("supplier_name")
                );
            }

            // Gets all active products
            java.sql.ResultSet rsProducts
                    = conn.createStatement().executeQuery(
                            "SELECT product_id, name "
                            + "FROM Products "
                            + "WHERE is_archived = 0"
                    );

            // Adds products into combo box
            while (rsProducts.next()) {

                cbProduct.addItem(
                        rsProducts.getInt("product_id")
                        + " - "
                        + rsProducts.getString("name")
                );
            }

        } catch (Exception e) {

            // Prints error in console
            e.printStackTrace();
            
            // Warns the user that dropdowns failed to populate
            JOptionPane.showMessageDialog(
                    this,
                    "Unable to load suppliers and products. Please check your connection and reopen this window.",
                    "System Error",
                    JOptionPane.ERROR_MESSAGE
            );
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        btnCancel = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtCostPrice = new javax.swing.JTextField();
        cbSupplier = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        cbProduct = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        txtQuantity = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setModal(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        btnCancel.setBackground(new java.awt.Color(241, 245, 249));
        btnCancel.setFont(new java.awt.Font("Geist SemiBold", 0, 12)); // NOI18N
        btnCancel.setText("Cancel");
        btnCancel.addActionListener(this::btnCancelActionPerformed);

        btnSave.setBackground(new java.awt.Color(227, 83, 10));
        btnSave.setFont(new java.awt.Font("Geist SemiBold", 0, 12)); // NOI18N
        btnSave.setForeground(new java.awt.Color(255, 255, 255));
        btnSave.setText("Save Purchase");
        btnSave.addActionListener(this::btnSaveActionPerformed);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSave)
                .addGap(14, 14, 14))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Geist", 0, 12)); // NOI18N
        jLabel1.setText("Supplier");

        jLabel3.setFont(new java.awt.Font("Geist", 0, 12)); // NOI18N
        jLabel3.setText("Cost Per Unit");

        txtCostPrice.setFont(new java.awt.Font("Geist", 0, 12)); // NOI18N
        txtCostPrice.addActionListener(this::txtCostPriceActionPerformed);

        cbSupplier.setFont(new java.awt.Font("Geist", 0, 12)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Geist", 0, 12)); // NOI18N
        jLabel2.setText("Product");

        cbProduct.setFont(new java.awt.Font("Geist", 0, 12)); // NOI18N
        cbProduct.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Rice Meals", "Burgers", "Fries", "Drinks", "Add-ons", "Desserts", "Noodles", "Pasta", "Pizza", "Appetizers", "Salads", "Soups", "Sandwiches", "Combos", "Snacks", "Specials", "Breakfast", "Lunch", "Dinner", "Catering" }));

        jLabel4.setFont(new java.awt.Font("Geist", 0, 12)); // NOI18N
        jLabel4.setText("Quantity");

        txtQuantity.setFont(new java.awt.Font("Geist", 0, 12)); // NOI18N
        txtQuantity.addActionListener(this::txtQuantityActionPerformed);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(52, 52, 52))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(82, 82, 82)))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel4)
                            .addGap(79, 79, 79)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(81, 81, 81)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txtQuantity)
                        .addComponent(txtCostPrice, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE)
                        .addComponent(cbProduct, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(cbSupplier, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(60, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cbSupplier, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtCostPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 102, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtCostPriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCostPriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCostPriceActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        // Closes dialog
        this.dispose();
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        try {

            // Gets supplier ID from combo box
            int supplierId =
                    Integer.parseInt(
                            cbSupplier.getSelectedItem()
                                    .toString()
                                    .split(" - ")[0]
                    );

            // Gets product ID from combo box
            int productId =
                    Integer.parseInt(
                            cbProduct.getSelectedItem()
                                    .toString()
                                    .split(" - ")[0]
                    );

            // Gets quantity input
            int quantity =
                    Integer.parseInt(
                            txtQuantity.getText().trim()
                    );

            // Gets cost price input
            double costPrice =
                    Double.parseDouble(
                            txtCostPrice.getText().trim()
                    );

            // Validation:
            // Quantity must be greater than 0
            // Cost price cannot be negative
            if (quantity <= 0 || costPrice < 0) {

                javax.swing.JOptionPane.showMessageDialog(
                        this,
                        "Quantity and Cost must be valid numbers.",
                        "Error",
                        javax.swing.JOptionPane.ERROR_MESSAGE
                );

                return;
            }

            // Connects to database
            java.sql.Connection conn =
                    database.DBConnection.getConnection();

            // Starts transaction mode
            // All queries must succeed together
            conn.setAutoCommit(false);

            try {

                // ================= PURCHASE TABLE =================

                // Inserts purchase record
                String sqlPurch =
                        "INSERT INTO Purchases " +
                        "(supplier_id, status) " +
                        "VALUES (?, 'Delivered')";

                // RETURN_GENERATED_KEYS gets new purchase ID
                java.sql.PreparedStatement pstmtPurch =
                        conn.prepareStatement(
                                sqlPurch,
                                java.sql.Statement.RETURN_GENERATED_KEYS
                        );

                // Inserts supplier ID
                pstmtPurch.setInt(1, supplierId);

                // Executes INSERT query
                pstmtPurch.executeUpdate();

                // Gets generated purchase ID
                java.sql.ResultSet rsKeys =
                        pstmtPurch.getGeneratedKeys();

                int purchaseId = 0;

                // Checks if purchase was created
                if (rsKeys.next()) {

                    // Gets new purchase ID
                    purchaseId = rsKeys.getInt(1);
                }

                // ================= PURCHASE DETAILS TABLE =================

                // Inserts purchase details
                String sqlDetails =
                        "INSERT INTO Purchase_Details " +
                        "(purchase_id, product_id, quantity_bought, cost_price) " +
                        "VALUES (?, ?, ?, ?)";

                java.sql.PreparedStatement pstmtDetails =
                        conn.prepareStatement(sqlDetails);

                // Inserts purchase ID
                pstmtDetails.setInt(1, purchaseId);

                // Inserts product ID
                pstmtDetails.setInt(2, productId);

                // Inserts quantity
                pstmtDetails.setInt(3, quantity);

                // Inserts cost price
                pstmtDetails.setDouble(4, costPrice);

                // Executes INSERT query
                pstmtDetails.executeUpdate();

                // ================= INVENTORY TABLE =================

                // Updates inventory stock
                String sqlInv =
                        "UPDATE Inventory " +
                        "SET current_stock = current_stock + ? " +
                        "WHERE product_id = ?";

                java.sql.PreparedStatement pstmtInv =
                        conn.prepareStatement(sqlInv);

                // Adds purchased quantity
                pstmtInv.setInt(1, quantity);

                // Selects correct product
                pstmtInv.setInt(2, productId);

                // Executes UPDATE query
                int rowsUpdated =
                        pstmtInv.executeUpdate();

                // If product does not exist in Inventory table
                if (rowsUpdated == 0) {

                    // Creates new inventory record
                    String sqlInsertInv =
                            "INSERT INTO Inventory " +
                            "(product_id, current_stock) " +
                            "VALUES (?, ?)";

                    java.sql.PreparedStatement pstmtInsertInv =
                            conn.prepareStatement(sqlInsertInv);

                    // Inserts product ID
                    pstmtInsertInv.setInt(1, productId);

                    // Inserts starting stock quantity
                    pstmtInsertInv.setInt(2, quantity);

                    // Executes INSERT query
                    pstmtInsertInv.executeUpdate();
                }

                // Saves all database changes permanently
                conn.commit();

                // Success message
                javax.swing.JOptionPane.showMessageDialog(
                        this,
                        "Purchase successful! Inventory has been restocked."
                );

                // Closes dialog
                this.dispose();

            } catch (Exception ex) {

                // Cancels all database changes if an error happens
                conn.rollback();

                // Throws error again
                throw ex;

            } finally {

                // Turns auto-commit back on
                conn.setAutoCommit(true);
            }

        } catch (NumberFormatException e) {

            // Runs if quantity or cost is not numeric
            JOptionPane.showMessageDialog(
                    this,
                    "Please enter valid numbers for quantity and cost.",
                    "Input Error",
                    JOptionPane.ERROR_MESSAGE
            );

        } catch (Exception e) {

            // Prints error in console
            e.printStackTrace();

            // Shows database/system error
            JOptionPane.showMessageDialog(
                    this,
                    "Unable to save purchase. Please try again.",
                    "Database Error",
                    JOptionPane.ERROR_MESSAGE
            );
        }
    }//GEN-LAST:event_btnSaveActionPerformed

    private void txtQuantityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtQuantityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtQuantityActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        // Opens dialog safely in Event Dispatch Thread
        java.awt.EventQueue.invokeLater(new Runnable() {

            @Override
            public void run() {

                // Creates dialog window
                AddPurchaseDialog dialog =
                        new AddPurchaseDialog(
                                new javax.swing.JFrame(),
                                true
                        );

                // Closes application when dialog closes
                dialog.addWindowListener(
                        new java.awt.event.WindowAdapter() {

                            @Override
                            public void windowClosing(
                                    java.awt.event.WindowEvent e) {

                                System.exit(0);
                            }
                        }
                );

                // Displays dialog
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnSave;
    private javax.swing.JComboBox<String> cbProduct;
    private javax.swing.JComboBox<String> cbSupplier;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTextField txtCostPrice;
    private javax.swing.JTextField txtQuantity;
    // End of variables declaration//GEN-END:variables
}
