package ui.dialogs;

// Imports database connection class
import database.DBConnection;

// Imports SQL classes
import java.sql.Connection;
import java.sql.PreparedStatement;

// Imports JOptionPane for message dialogs
import javax.swing.JOptionPane;

public class AddProductDialog extends javax.swing.JDialog {

    // Logger used for debugging or tracking errors
    private static final java.util.logging.Logger logger
            = java.util.logging.Logger.getLogger(
                    AddProductDialog.class.getName()
            );

    // Constructor
    // Creates the dialog window
    public AddProductDialog(java.awt.Frame parent, boolean modal) {

        // Calls parent constructor
        super(parent, modal);

        // Initializes all UI components
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        btnCancel = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtProductName = new javax.swing.JTextField();
        txtPrice = new javax.swing.JTextField();
        cbCategory = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setModal(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        btnCancel.setBackground(new java.awt.Color(241, 245, 249));
        btnCancel.setFont(new java.awt.Font("Geist SemiBold", 0, 12)); // NOI18N
        btnCancel.setText("Cancel");
        btnCancel.addActionListener(this::btnCancelActionPerformed);

        btnSave.setBackground(new java.awt.Color(227, 83, 10));
        btnSave.setFont(new java.awt.Font("Geist SemiBold", 0, 12)); // NOI18N
        btnSave.setForeground(new java.awt.Color(255, 255, 255));
        btnSave.setText("Save Product");
        btnSave.addActionListener(this::btnSaveActionPerformed);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSave)
                .addGap(14, 14, 14))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Geist", 0, 12)); // NOI18N
        jLabel1.setText("Product Name");

        jLabel2.setFont(new java.awt.Font("Geist", 0, 12)); // NOI18N
        jLabel2.setText("Price (PHP)");

        jLabel3.setFont(new java.awt.Font("Geist", 0, 12)); // NOI18N
        jLabel3.setText("Category");

        txtProductName.setFont(new java.awt.Font("Geist", 0, 12)); // NOI18N
        txtProductName.addActionListener(this::txtProductNameActionPerformed);

        txtPrice.setFont(new java.awt.Font("Geist", 0, 12)); // NOI18N
        txtPrice.addActionListener(this::txtPriceActionPerformed);

        cbCategory.setFont(new java.awt.Font("Geist", 0, 12)); // NOI18N
        cbCategory.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Rice Meals", "Burgers", "Fries", "Drinks", "Add-ons", "Desserts", "Noodles", "Pasta", "Pizza", "Appetizers", "Salads", "Soups", "Sandwiches", "Combos", "Snacks", "Specials", "Breakfast", "Lunch", "Dinner", "Catering" }));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addGap(69, 69, 69))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel3)
                            .addGap(84, 84, 84)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(56, 56, 56)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtProductName, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbCategory, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(56, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtProductName, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbCategory, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 82, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtProductNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtProductNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtProductNameActionPerformed

    private void txtPriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPriceActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        // Closes the dialog
        this.dispose();
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // Gets product name from text field
        String name =
                txtProductName.getText().trim();

        // Gets selected category
        String category =
                cbCategory.getSelectedItem().toString();

        // Gets price input
        String priceText =
                txtPrice.getText().trim();

        // Validation:
        // Checks if product name or price is empty
        if (name.isEmpty() || priceText.isEmpty()) {

            JOptionPane.showMessageDialog(
                    this,
                    "Please fill in all fields before saving.",
                    "Missing Data",
                    JOptionPane.WARNING_MESSAGE
            );

            return;
        }

        try {

            // Converts price text into double value
            double price =
                    Double.parseDouble(priceText);

            // Validation:
            // Price must be greater than 0
            if (price <= 0) {

                JOptionPane.showMessageDialog(
                        this,
                        "Product price must be greater than 0!",
                        "Invalid Price",
                        JOptionPane.WARNING_MESSAGE
                );

                return;
            }

            // Gets category ID based on combo box index
            // +1 because database IDs start at 1
            int categoryId =
                    cbCategory.getSelectedIndex() + 1;

            // Connects to database
            Connection conn =
                    DBConnection.getConnection();

            // SQL query for inserting product
            String sql =
                    "INSERT INTO Products " +
                    "(name, category_id, price, is_archived) " +
                    "VALUES (?, ?, ?, 0)";

            // Creates PreparedStatement
            // RETURN_GENERATED_KEYS gets the new product ID
            PreparedStatement pstmt =
                    conn.prepareStatement(
                            sql,
                            java.sql.Statement.RETURN_GENERATED_KEYS
                    );

            // Inserts product name
            pstmt.setString(1, name);

            // Inserts category ID
            pstmt.setInt(2, categoryId);

            // Inserts product price
            pstmt.setDouble(3, price);

            // Executes INSERT query
            pstmt.executeUpdate();

            // Gets the generated product ID
            java.sql.ResultSet rs =
                    pstmt.getGeneratedKeys();

            // Checks if product was inserted successfully
            if (rs.next()) {

                // Gets newly created product ID
                int newProductId =
                        rs.getInt(1);

                // Automatically creates inventory record
                String invSql =
                        "INSERT INTO Inventory " +
                        "(product_id, current_stock) " +
                        "VALUES (?, 0)";

                // Creates PreparedStatement for Inventory table
                PreparedStatement invPstmt =
                        conn.prepareStatement(invSql);

                // Inserts product ID into Inventory table
                invPstmt.setInt(1, newProductId);

                // Executes inventory insert query
                invPstmt.executeUpdate();
            }

            // Success message
            JOptionPane.showMessageDialog(
                    this,
                    "Product Added Successfully!"
            );

            // Closes dialog
            this.dispose();

        } catch (NumberFormatException e) {

            // Runs if price is not numeric
            JOptionPane.showMessageDialog(
                    this,
                    "Price must be a valid number!",
                    "Input Error",
                    JOptionPane.ERROR_MESSAGE
            );

        } catch (Exception e) {

            // 1. Prints the raw SQL error in the console for you (the developer)
            e.printStackTrace();

            // 2. Gets the SQL error text secretly
            String errorMsg = e.getMessage().toLowerCase();

            // 3. Checks if the SQL error is complaining about a duplicate
            if (errorMsg != null && (errorMsg.contains("unique") || errorMsg.contains("duplicate") || errorMsg.contains("primary key"))) {

                javax.swing.JOptionPane.showMessageDialog(
                        this,
                        "This record already exists! You cannot add a duplicate.",
                        "Duplicate Found",
                        javax.swing.JOptionPane.WARNING_MESSAGE
                );

            } else {

                // 4. For all other random database errors (like server disconnects)
                javax.swing.JOptionPane.showMessageDialog(
                        this,
                        "A system error occurred while trying to save. Please try again.",
                        "System Error",
                        javax.swing.JOptionPane.ERROR_MESSAGE
                );
            }
        }
    }//GEN-LAST:event_btnSaveActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        // Opens dialog safely in Event Dispatch Thread
        java.awt.EventQueue.invokeLater(new Runnable() {

            @Override
            public void run() {

                // Creates dialog window
                AddProductDialog dialog =
                        new AddProductDialog(
                                new javax.swing.JFrame(),
                                true
                        );

                // Closes application when dialog closes
                dialog.addWindowListener(
                        new java.awt.event.WindowAdapter() {

                            @Override
                            public void windowClosing(
                                    java.awt.event.WindowEvent e) {

                                System.exit(0);
                            }
                        }
                );

                // Displays dialog
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnSave;
    private javax.swing.JComboBox<String> cbCategory;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTextField txtPrice;
    private javax.swing.JTextField txtProductName;
    // End of variables declaration//GEN-END:variables
}
