package ui.dialogs;

// Imports JOptionPane for popup messages
import javax.swing.JOptionPane;

public class EditSupplierDialog extends javax.swing.JDialog {

    // Logger used for debugging or tracking errors
    private static final java.util.logging.Logger logger
            = java.util.logging.Logger.getLogger(
                    EditSupplierDialog.class.getName()
            );

    // Stores the selected supplier ID
    private int currentSupplierId;

    // Default constructor
    public EditSupplierDialog(java.awt.Frame parent, boolean modal) {

        // Calls parent constructor
        super(parent, modal);

        // Initializes all UI components
        initComponents();
    }

    // Constructor used when editing a supplier
    public EditSupplierDialog(
            java.awt.Frame parent,
            boolean modal,
            int supplierId,
            String name,
            String address,
            String phone
    ) {

        // Calls parent constructor
        super(parent, modal);

        // Initializes all UI components
        initComponents();

        // Stores selected supplier ID
        this.currentSupplierId = supplierId;

        // Displays existing supplier information
        txtCompanyName.setText(name);
        txtAddress.setText(address);
        txtPhone.setText(phone);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        btnCancel = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtCompanyName = new javax.swing.JTextField();
        txtAddress = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtPhone = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setModal(true);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnCancel.setBackground(new java.awt.Color(241, 245, 249));
        btnCancel.setFont(new java.awt.Font("Geist SemiBold", 0, 12)); // NOI18N
        btnCancel.setText("Cancel");
        btnCancel.addActionListener(this::btnCancelActionPerformed);

        btnSave.setBackground(new java.awt.Color(227, 83, 10));
        btnSave.setFont(new java.awt.Font("Geist SemiBold", 0, 12)); // NOI18N
        btnSave.setForeground(new java.awt.Color(255, 255, 255));
        btnSave.setText("Update Supplier");
        btnSave.addActionListener(this::btnSaveActionPerformed);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSave)
                .addGap(14, 14, 14))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jPanel2.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 273, 430, -1));

        jLabel1.setFont(new java.awt.Font("Geist", 0, 12)); // NOI18N
        jLabel1.setText("Company Name");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, -1, -1));

        jLabel2.setFont(new java.awt.Font("Geist", 0, 12)); // NOI18N
        jLabel2.setText("Address");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, -1, -1));

        txtCompanyName.setFont(new java.awt.Font("Geist", 0, 12)); // NOI18N
        txtCompanyName.addActionListener(this::txtCompanyNameActionPerformed);
        jPanel2.add(txtCompanyName, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 80, 240, 30));

        txtAddress.setFont(new java.awt.Font("Geist", 0, 12)); // NOI18N
        txtAddress.addActionListener(this::txtAddressActionPerformed);
        jPanel2.add(txtAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 120, 240, 30));

        jLabel4.setFont(new java.awt.Font("Geist", 0, 12)); // NOI18N
        jLabel4.setText("Phone Number");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, -1, -1));

        txtPhone.setFont(new java.awt.Font("Geist", 0, 12)); // NOI18N
        txtPhone.addActionListener(this::txtPhoneActionPerformed);
        jPanel2.add(txtPhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 160, 240, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtCompanyNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCompanyNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCompanyNameActionPerformed

    private void txtAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAddressActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        // Closes dialog
        this.dispose();
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // Gets updated supplier name
        String company
                = txtCompanyName.getText().trim();

        // Gets updated phone number
        String contactNo
                = txtPhone.getText().trim();

        // Gets updated address
        String address
                = txtAddress.getText().trim();

        // Validation:
        // Checks if fields are empty
        if (company.isEmpty()
                || contactNo.isEmpty()
                || address.isEmpty()) {

            javax.swing.JOptionPane.showMessageDialog(
                    this,
                    "Please fill in all supplier fields.",
                    "Validation Error",
                    javax.swing.JOptionPane.WARNING_MESSAGE
            );

            return;
        }

        // Validation:
        // Phone number must contain numbers only
        if (!contactNo.matches("\\d+")) {

            JOptionPane.showMessageDialog(
                    this,
                    "Phone number must contain numbers only!",
                    "Invalid Phone Number",
                    JOptionPane.WARNING_MESSAGE
            );

            return;
        }

        try {

            // Connects to database
            java.sql.Connection conn
                    = database.DBConnection.getConnection();

            // SQL query for updating supplier
            String sql
                    = "UPDATE Suppliers "
                    + "SET supplier_name = ?, "
                    + "contact_no = ?, "
                    + "address = ? "
                    + "WHERE supplier_id = ?";

            // Creates PreparedStatement
            java.sql.PreparedStatement pstmt
                    = conn.prepareStatement(sql);

            // Updates supplier name
            pstmt.setString(1, company);

            // Updates phone number
            pstmt.setString(2, contactNo);

            // Updates address
            pstmt.setString(3, address);

            // Selects correct supplier using supplier ID
            pstmt.setInt(4, currentSupplierId);

            // Executes UPDATE query
            pstmt.executeUpdate();

            // Success message
            javax.swing.JOptionPane.showMessageDialog(
                    this,
                    "Supplier updated successfully!"
            );

            // Closes dialog
            this.dispose();

        } catch (Exception e) {

            // Prints error in console
            e.printStackTrace();

            // Shows database/system error
            javax.swing.JOptionPane.showMessageDialog(
                    this,
                    "Database Error: " + e.getMessage(),
                    "Error",
                    javax.swing.JOptionPane.ERROR_MESSAGE
            );
        }
    }//GEN-LAST:event_btnSaveActionPerformed

    private void txtPhoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPhoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPhoneActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        // Opens dialog safely in Event Dispatch Thread
        java.awt.EventQueue.invokeLater(new Runnable() {

            @Override
            public void run() {

                // Creates dialog window
                EditSupplierDialog dialog
                        = new EditSupplierDialog(
                                new javax.swing.JFrame(),
                                true
                        );

                // Closes application when dialog closes
                dialog.addWindowListener(
                        new java.awt.event.WindowAdapter() {

                    @Override
                    public void windowClosing(
                            java.awt.event.WindowEvent e) {

                        System.exit(0);
                    }
                }
                );

                // Displays dialog
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnSave;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTextField txtAddress;
    private javax.swing.JTextField txtCompanyName;
    private javax.swing.JTextField txtPhone;
    // End of variables declaration//GEN-END:variables
}
