package ui.dialogs;

import com.formdev.flatlaf.FlatClientProperties;
import ui.menuPanel.POSPanel;

public class ProductCard extends javax.swing.JPanel {

    private int productId;
    private String productName;
    private double productPrice;
    private POSPanel parentPOS;

    public ProductCard(int id, String name, double price, POSPanel pos) {
        initComponents();
        
        jPanel2.putClientProperty(
                FlatClientProperties.STYLE,
                "arc:20;"
                + "background:#FFFFFF;"
                + "border:8,8,8,8,#E5E7EB;"
        );
        this.productId = id;
        this.productName = name;
        this.productPrice = price;
        this.parentPOS = pos;

        lblProductName.setText(name);
        lblPrice.setText(String.format("%.2f", price));

        this.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                parentPOS.addToCart(productId, productName, productPrice);
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        lblProductImage = new javax.swing.JPanel();
        lblProductName = new javax.swing.JLabel();
        Total = new javax.swing.JLabel();
        lblPrice = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(160, 180));
        setMinimumSize(new java.awt.Dimension(160, 180));
        setPreferredSize(new java.awt.Dimension(160, 180));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setMaximumSize(new java.awt.Dimension(160, 180));
        jPanel2.setMinimumSize(new java.awt.Dimension(160, 180));
        jPanel2.setPreferredSize(new java.awt.Dimension(160, 180));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblProductImage.setBackground(new java.awt.Color(230, 230, 230));
        lblProductImage.setMaximumSize(new java.awt.Dimension(140, 100));
        lblProductImage.setMinimumSize(new java.awt.Dimension(140, 100));
        lblProductImage.setPreferredSize(new java.awt.Dimension(140, 100));
        jPanel2.add(lblProductImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 160, 80));

        lblProductName.setFont(new java.awt.Font("Geist", 0, 14)); // NOI18N
        lblProductName.setText("Item Name");
        jPanel2.add(lblProductName, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 80, -1));

        Total.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        Total.setText("₱");
        jPanel2.add(Total, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, -1, -1));

        lblPrice.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        lblPrice.setText(" 0.00");
        jPanel2.add(lblPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, 20));

        add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Total;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblPrice;
    private javax.swing.JPanel lblProductImage;
    private javax.swing.JLabel lblProductName;
    // End of variables declaration//GEN-END:variables
}
