package ui.menuPanel;

// Imports Swing constants for table alignment
import javax.swing.SwingConstants;

// Imports table cell renderer
import javax.swing.table.DefaultTableCellRenderer;

// Imports LoginPanel to get logged-in user ID
import ui.auth.LoginPanel;

public class ExpensesPanel extends javax.swing.JPanel {

    // Constructor
    // Runs when ExpensesPanel is created
    public ExpensesPanel() {

        // Initializes all UI components
        initComponents();

        // Styles the table header font
        tblExpenses.getTableHeader().setFont(
                new java.awt.Font(
                        "Geist SemiBold",
                        java.awt.Font.PLAIN,
                        10
                )
        );

        // Changes table header background color
        tblExpenses.getTableHeader().setBackground(
                new java.awt.Color(245, 245, 245)
        );

        // Changes table header text color
        tblExpenses.getTableHeader().setForeground(
                new java.awt.Color(80, 80, 80)
        );

        // Removes spacing between table cells
        tblExpenses.setIntercellSpacing(
                new java.awt.Dimension(0, 0)
        );

        // Removes table grid lines
        tblExpenses.setShowGrid(false);

        // Sets row height
        tblExpenses.setRowHeight(35);

        // Creates center alignment renderer
        DefaultTableCellRenderer centerRenderer
                = new DefaultTableCellRenderer();

        // Centers text horizontally
        centerRenderer.setHorizontalAlignment(
                SwingConstants.CENTER
        );

        // Applies center alignment to all columns
        for (int i = 0; i < tblExpenses.getColumnCount(); i++) {

            tblExpenses.getColumnModel()
                    .getColumn(i)
                    .setCellRenderer(centerRenderer);
        }

        // Loads expense records into table
        loadExpenses();
    }

    // Loads expense records from database
    public void loadExpenses() {

        // SQL query for retrieving expense records
        String sql
                = "SELECT expense_id, "
                + "date_paid, "
                + "category, "
                + "amount, "
                + "status, "
                + "description "
                + "FROM Expenses "
                + "ORDER BY expense_id DESC";

        try (
                // Connects to database
                java.sql.Connection conn
                = database.DBConnection.getConnection(); // Creates PreparedStatement
                 java.sql.PreparedStatement pstmt
                = conn.prepareStatement(sql); // Executes SELECT query
                 java.sql.ResultSet rs
                = pstmt.executeQuery()) {

            // Gets table model
            javax.swing.table.DefaultTableModel model
                    = (javax.swing.table.DefaultTableModel) tblExpenses.getModel();

            // Clears existing rows
            model.setRowCount(0);

            // Date format for displaying expense date
            java.text.SimpleDateFormat sdf
                    = new java.text.SimpleDateFormat(
                            "MMM dd, yyyy - hh:mm a"
                    );

            // Loops through database records
            while (rs.next()) {

                // Adds row into table
                model.addRow(new Object[]{
                    rs.getInt("expense_id"),
                    // Formats date and time
                    sdf.format(
                    rs.getTimestamp("date_paid")
                    ),
                    rs.getString("category"),
                    rs.getDouble("amount"),
                    rs.getString("status"),
                    // Displays blank if description is null
                    rs.getString("description") == null
                    ? ""
                    : rs.getString("description")
                });
            }

        } catch (Exception e) {
            // Prints error in console for developers
            e.printStackTrace();

            // Shows safe error to user
            javax.swing.JOptionPane.showMessageDialog(
                    this,
                    "Unable to load expenses at this time. Please check your connection and try again.",
                    "System Error",
                    javax.swing.JOptionPane.ERROR_MESSAGE
            );
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cardContainer = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnRecordExpense = new javax.swing.JButton();
        btnVoidExpense = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblExpenses = new javax.swing.JTable();

        setBackground(new java.awt.Color(248, 250, 252));
        setLayout(new java.awt.GridBagLayout());

        cardContainer.setBackground(new java.awt.Color(255, 255, 255));
        cardContainer.setMaximumSize(new java.awt.Dimension(980, 610));
        cardContainer.setMinimumSize(new java.awt.Dimension(980, 610));
        cardContainer.setPreferredSize(new java.awt.Dimension(980, 610));
        cardContainer.setRequestFocusEnabled(false);
        cardContainer.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(226, 232, 240)));

        jLabel1.setFont(new java.awt.Font("Georgia", 1, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(15, 23, 42));
        jLabel1.setText("Operating Expenses");

        btnRecordExpense.setBackground(new java.awt.Color(231, 90, 14));
        btnRecordExpense.setFont(new java.awt.Font("Geist SemiBold", 0, 12)); // NOI18N
        btnRecordExpense.setForeground(new java.awt.Color(255, 255, 255));
        btnRecordExpense.setText("Record Expense");
        btnRecordExpense.setMaximumSize(new java.awt.Dimension(102, 24));
        btnRecordExpense.setMinimumSize(new java.awt.Dimension(102, 24));
        btnRecordExpense.setPreferredSize(new java.awt.Dimension(102, 24));
        btnRecordExpense.addActionListener(this::btnRecordExpenseActionPerformed);

        btnVoidExpense.setBackground(new java.awt.Color(254, 226, 226));
        btnVoidExpense.setFont(new java.awt.Font("Geist SemiBold", 0, 12)); // NOI18N
        btnVoidExpense.setForeground(new java.awt.Color(153, 27, 27));
        btnVoidExpense.setText("Void");
        btnVoidExpense.setPreferredSize(new java.awt.Dimension(113, 30));
        btnVoidExpense.addActionListener(this::btnVoidExpenseActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 536, Short.MAX_VALUE)
                .addComponent(btnRecordExpense, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnVoidExpense, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnVoidExpense, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnRecordExpense, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 11, Short.MAX_VALUE)))
                .addGap(13, 13, 13))
        );

        cardContainer.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 980, 70));

        tblExpenses.setFont(new java.awt.Font("Geist", 0, 12)); // NOI18N
        tblExpenses.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Expense ID", "Date", "Category", "Amount", "Status", "Remarks"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblExpenses.setRowHeight(35);
        jScrollPane1.setViewportView(tblExpenses);

        cardContainer.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 940, 500));

        add(cardContainer, new java.awt.GridBagConstraints());
    }// </editor-fold>//GEN-END:initComponents

    private void btnRecordExpenseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRecordExpenseActionPerformed
        // Gets current window
        java.awt.Window parentWindow
                = javax.swing.SwingUtilities
                        .getWindowAncestor(this);

        // Converts window into Frame
        java.awt.Frame parentFrame
                = (parentWindow instanceof java.awt.Frame)
                        ? (java.awt.Frame) parentWindow
                        : null;

        // Opens AddExpenseDialog
        ui.dialogs.AddExpenseDialog dialog
                = new ui.dialogs.AddExpenseDialog(
                        parentFrame,
                        true
                );

        // Centers dialog relative to parent frame
        dialog.setLocationRelativeTo(parentFrame);

        // Displays dialog
        dialog.setVisible(true);

        // Reloads updated expense records
        loadExpenses();
    }//GEN-LAST:event_btnRecordExpenseActionPerformed

    private void btnVoidExpenseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoidExpenseActionPerformed
        // Gets selected row in table
        int selectedRow
                = tblExpenses.getSelectedRow();

        // Validation:
        // Checks if user selected a row
        if (selectedRow == -1) {

            javax.swing.JOptionPane.showMessageDialog(
                    this,
                    "Please select an expense record to void.",
                    "No Selection",
                    javax.swing.JOptionPane.WARNING_MESSAGE
            );

            return;
        }

        // Gets selected expense ID
        int expenseId
                = (int) tblExpenses.getValueAt(
                        selectedRow,
                        0
                );

        // Gets current expense status
        String currentStatus
                = (String) tblExpenses.getValueAt(
                        selectedRow,
                        4
                );

        // Validation:
        // Checks if expense is already cancelled
        if ("Cancelled".equalsIgnoreCase(currentStatus)) {

            javax.swing.JOptionPane.showMessageDialog(
                    this,
                    "This expense record has already been voided.",
                    "Information",
                    javax.swing.JOptionPane.INFORMATION_MESSAGE
            );

            return;
        }

        // Confirmation dialog
        int confirm
                = javax.swing.JOptionPane.showConfirmDialog(
                        this,
                        "Are you sure you want to void Expense Record #"
                        + expenseId + "?",
                        "Confirm Void",
                        javax.swing.JOptionPane.YES_NO_OPTION,
                        javax.swing.JOptionPane.WARNING_MESSAGE
                );

        // Runs if user clicks YES
        if (confirm == javax.swing.JOptionPane.YES_OPTION) {

            try (
                    // Connects to database
                    java.sql.Connection conn
                    = database.DBConnection.getConnection()) {

                // SQL query for cancelling expense
                String sql
                        = "UPDATE Expenses "
                        + "SET status = 'Cancelled' "
                        + "WHERE expense_id = ?";

                try (
                        // Creates PreparedStatement
                        java.sql.PreparedStatement pstmt
                        = conn.prepareStatement(sql)) {

                    // Selects correct expense ID
                    pstmt.setInt(1, expenseId);

                    // Executes UPDATE query
                    pstmt.executeUpdate();
                }

                // SQL query for Audit Log
                String logSql
                        = "INSERT INTO AuditLogs "
                        + "(user_id, action, description) "
                        + "VALUES (?, 'VOID_EXPENSE', ?)";

                try (
                        // Creates PreparedStatement
                        java.sql.PreparedStatement logStmt
                        = conn.prepareStatement(logSql)) {

                    // Inserts logged-in user ID
                    logStmt.setInt(
                            1,
                            LoginPanel.loggedInUserId
                    );

                    // Inserts audit description
                    logStmt.setString(
                            2,
                            "Voided expense entry ID: "
                            + expenseId
                    );

                    // Executes INSERT query
                    logStmt.executeUpdate();
                }

                // Success message
                javax.swing.JOptionPane.showMessageDialog(
                        this,
                        "Expense entry marked as Cancelled."
                );

                // Reloads updated expense records
                loadExpenses();

            } catch (Exception e) {
                // Prints error in console for developers
                e.printStackTrace();

                // Shows safe error to user
                javax.swing.JOptionPane.showMessageDialog(
                        this,
                        "An error occurred while trying to void this expense. Please contact the administrator.",
                        "System Error",
                        javax.swing.JOptionPane.ERROR_MESSAGE
                );
            }
        }
    }//GEN-LAST:event_btnVoidExpenseActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRecordExpense;
    private javax.swing.JButton btnVoidExpense;
    private javax.swing.JPanel cardContainer;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblExpenses;
    // End of variables declaration//GEN-END:variables
}
