package ui.menuPanel;

import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import ui.auth.LoginPanel;

public class ExpensesPanel extends javax.swing.JPanel {

    public ExpensesPanel() {
        initComponents();

        tblExpenses.getTableHeader().setFont(new java.awt.Font("Geist SemiBold", java.awt.Font.PLAIN, 10));
        tblExpenses.getTableHeader().setBackground(new java.awt.Color(245, 245, 245));
        tblExpenses.getTableHeader().setForeground(new java.awt.Color(80, 80, 80));
        tblExpenses.setIntercellSpacing(new java.awt.Dimension(0, 0));
        tblExpenses.setShowGrid(false);
        tblExpenses.setRowHeight(35);
        
        
        DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
        centerRenderer.setHorizontalAlignment(SwingConstants.CENTER);

        for (int i = 0; i < tblExpenses.getColumnCount(); i++) {
            tblExpenses.getColumnModel().getColumn(i).setCellRenderer(centerRenderer);
        }

        loadExpenses();
    }

    public void loadExpenses() {
        String sql = "SELECT expense_id, date_paid, category, amount, status, description FROM Expenses ORDER BY date_paid DESC";

        try (java.sql.Connection conn = database.DBConnection.getConnection(); java.sql.PreparedStatement pstmt = conn.prepareStatement(sql); java.sql.ResultSet rs = pstmt.executeQuery()) {

            javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) tblExpenses.getModel();
            model.setRowCount(0);

            java.text.SimpleDateFormat sdf = new java.text.SimpleDateFormat("MMM dd, yyyy - hh:mm a");

            while (rs.next()) {
                model.addRow(new Object[]{
                    rs.getInt("expense_id"),
                    sdf.format(rs.getTimestamp("date_paid")),
                    rs.getString("category"),
                    rs.getDouble("amount"),
                    rs.getString("status"),
                    rs.getString("description") == null ? "" : rs.getString("description")
                });
            }

        } catch (Exception e) {
            e.printStackTrace();
            javax.swing.JOptionPane.showMessageDialog(this, "Error loading expenses: " + e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cardContainer = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnRecordExpense = new javax.swing.JButton();
        btnVoidExpense = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblExpenses = new javax.swing.JTable();

        setBackground(new java.awt.Color(248, 250, 252));
        setLayout(new java.awt.GridBagLayout());

        cardContainer.setBackground(new java.awt.Color(255, 255, 255));
        cardContainer.setMaximumSize(new java.awt.Dimension(980, 610));
        cardContainer.setMinimumSize(new java.awt.Dimension(980, 610));
        cardContainer.setPreferredSize(new java.awt.Dimension(980, 610));
        cardContainer.setRequestFocusEnabled(false);
        cardContainer.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(226, 232, 240)));

        jLabel1.setFont(new java.awt.Font("Georgia", 1, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(15, 23, 42));
        jLabel1.setText("Operating Expenses");

        btnRecordExpense.setBackground(new java.awt.Color(231, 90, 14));
        btnRecordExpense.setFont(new java.awt.Font("Geist SemiBold", 0, 12)); // NOI18N
        btnRecordExpense.setForeground(new java.awt.Color(255, 255, 255));
        btnRecordExpense.setText("Record Expense");
        btnRecordExpense.setMaximumSize(new java.awt.Dimension(102, 24));
        btnRecordExpense.setMinimumSize(new java.awt.Dimension(102, 24));
        btnRecordExpense.setPreferredSize(new java.awt.Dimension(102, 24));
        btnRecordExpense.addActionListener(this::btnRecordExpenseActionPerformed);

        btnVoidExpense.setBackground(new java.awt.Color(254, 226, 226));
        btnVoidExpense.setFont(new java.awt.Font("Geist SemiBold", 0, 12)); // NOI18N
        btnVoidExpense.setForeground(new java.awt.Color(153, 27, 27));
        btnVoidExpense.setText("Void");
        btnVoidExpense.setPreferredSize(new java.awt.Dimension(113, 30));
        btnVoidExpense.addActionListener(this::btnVoidExpenseActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 536, Short.MAX_VALUE)
                .addComponent(btnRecordExpense, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnVoidExpense, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnVoidExpense, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnRecordExpense, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 11, Short.MAX_VALUE)))
                .addGap(13, 13, 13))
        );

        cardContainer.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 980, 70));

        tblExpenses.setFont(new java.awt.Font("Geist", 0, 12)); // NOI18N
        tblExpenses.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Expense ID", "Date", "Category", "Amount", "Status", "Remarks"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblExpenses.setRowHeight(35);
        jScrollPane1.setViewportView(tblExpenses);

        cardContainer.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 940, 500));

        add(cardContainer, new java.awt.GridBagConstraints());
    }// </editor-fold>//GEN-END:initComponents

    private void btnRecordExpenseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRecordExpenseActionPerformed
        java.awt.Window parentWindow = javax.swing.SwingUtilities.getWindowAncestor(this);
        java.awt.Frame parentFrame = (parentWindow instanceof java.awt.Frame) ? (java.awt.Frame) parentWindow : null;

        ui.dialogs.AddExpenseDialog dialog = new ui.dialogs.AddExpenseDialog(parentFrame, true);
        dialog.setLocationRelativeTo(parentFrame);
        dialog.setVisible(true);

        loadExpenses();
    }//GEN-LAST:event_btnRecordExpenseActionPerformed

    private void btnVoidExpenseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoidExpenseActionPerformed
        int selectedRow = tblExpenses.getSelectedRow();

        if (selectedRow == -1) {
            javax.swing.JOptionPane.showMessageDialog(this, "Please select an expense record to void.", "No Selection", javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }

        int expenseId = (int) tblExpenses.getValueAt(selectedRow, 0);
        String currentStatus = (String) tblExpenses.getValueAt(selectedRow, 4);

        if ("Cancelled".equalsIgnoreCase(currentStatus)) {
            javax.swing.JOptionPane.showMessageDialog(this, "This expense record has already been voided.", "Information", javax.swing.JOptionPane.INFORMATION_MESSAGE);
            return;
        }

        int confirm = javax.swing.JOptionPane.showConfirmDialog(this,
                "Are you sure you want to void Expense Record #" + expenseId + "?",
                "Confirm Void",
                javax.swing.JOptionPane.YES_NO_OPTION,
                javax.swing.JOptionPane.WARNING_MESSAGE);

        if (confirm == javax.swing.JOptionPane.YES_OPTION) {

            try (java.sql.Connection conn = database.DBConnection.getConnection()) {

                String sql = "UPDATE Expenses SET status = 'Cancelled' WHERE expense_id = ?";

                try (java.sql.PreparedStatement pstmt = conn.prepareStatement(sql)) {
                    pstmt.setInt(1, expenseId);
                    pstmt.executeUpdate();
                }

                String logSql = "INSERT INTO AuditLogs (user_id, action, description) VALUES (?, 'VOID_EXPENSE', ?)";

                try (java.sql.PreparedStatement logStmt = conn.prepareStatement(logSql)) {
                    logStmt.setInt(1, LoginPanel.loggedInUserId);
                    logStmt.setString(2, "Voided expense entry ID: " + expenseId);
                    logStmt.executeUpdate();
                }

                javax.swing.JOptionPane.showMessageDialog(this, "Expense entry marked as Cancelled.");
                loadExpenses();

            } catch (Exception e) {
                e.printStackTrace();
                javax.swing.JOptionPane.showMessageDialog(this, "Database Error: " + e.getMessage(), "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnVoidExpenseActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRecordExpense;
    private javax.swing.JButton btnVoidExpense;
    private javax.swing.JPanel cardContainer;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblExpenses;
    // End of variables declaration//GEN-END:variables
}
