package ui.menuPanel;

import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;

public class InventoryPanel extends javax.swing.JPanel {

    public InventoryPanel() {
        initComponents();

        tblInventory.getTableHeader().setFont(
                new java.awt.Font("Geist SemiBold", java.awt.Font.PLAIN, 10)
        );
        tblInventory.getTableHeader().setBackground(
                new java.awt.Color(245, 245, 245)
        );
        tblInventory.getTableHeader().setForeground(
                new java.awt.Color(80, 80, 80)
        );
        tblInventory.setIntercellSpacing(new java.awt.Dimension(0, 0));
        tblInventory.setShowGrid(false);

        DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
        centerRenderer.setHorizontalAlignment(SwingConstants.CENTER);

        for (int i = 0; i < tblInventory.getColumnCount(); i++) {
            tblInventory.getColumnModel().getColumn(i).setCellRenderer(centerRenderer);
        }

        loadInventoryToTable();
    }

    public void loadInventoryToTable() {
        try {
            java.sql.Connection conn = database.DBConnection.getConnection();

            String sql = "SELECT p.product_id, p.name, ISNULL(i.current_stock, 0) AS current_stock "
                    + "FROM Products p "
                    + "LEFT JOIN Inventory i ON p.product_id = i.product_id "
                    + "WHERE p.is_archived = 0 "
                    + "ORDER BY p.name ASC";

            java.sql.PreparedStatement pstmt = conn.prepareStatement(sql);
            java.sql.ResultSet rs = pstmt.executeQuery();

            javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) tblInventory.getModel();
            model.setRowCount(0);

            while (rs.next()) {
                int stock = rs.getInt("current_stock");

                String status = (stock == 0) ? "Out of Stock" : (stock <= 15) ? "Low Stock" : "In Stock";

                model.addRow(new Object[]{
                    rs.getInt("product_id"),
                    rs.getString("name"),
                    stock,
                    status
                });
            }
        } catch (Exception e) {
            e.printStackTrace();
            javax.swing.JOptionPane.showMessageDialog(this, "Error loading inventory: " + e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cardContainer = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnUpdate = new javax.swing.JButton();
        Export = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblInventory = new javax.swing.JTable();

        setBackground(new java.awt.Color(248, 250, 252));
        setLayout(new java.awt.GridBagLayout());

        cardContainer.setBackground(new java.awt.Color(255, 255, 255));
        cardContainer.setMaximumSize(new java.awt.Dimension(980, 610));
        cardContainer.setMinimumSize(new java.awt.Dimension(980, 610));
        cardContainer.setPreferredSize(new java.awt.Dimension(980, 610));
        cardContainer.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(226, 232, 240)));

        jLabel1.setFont(new java.awt.Font("Georgia", 1, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(15, 23, 42));
        jLabel1.setText("Inventory Stock Monitor");

        btnUpdate.setBackground(new java.awt.Color(227, 83, 10));
        btnUpdate.setFont(new java.awt.Font("Geist SemiBold", 0, 12)); // NOI18N
        btnUpdate.setForeground(new java.awt.Color(255, 255, 255));
        btnUpdate.setText("Update Stock");
        btnUpdate.setPreferredSize(new java.awt.Dimension(100, 35));
        btnUpdate.addActionListener(this::btnUpdateActionPerformed);

        Export.setFont(new java.awt.Font("Geist SemiBold", 0, 12)); // NOI18N
        Export.setForeground(new java.awt.Color(102, 102, 102));
        Export.setText("Export to CSV");
        Export.setPreferredSize(new java.awt.Dimension(100, 35));
        Export.addActionListener(this::ExportActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 441, Short.MAX_VALUE)
                .addComponent(Export, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(Export, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        cardContainer.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 980, 70));

        tblInventory.setFont(new java.awt.Font("Geist", 0, 12)); // NOI18N
        tblInventory.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Product ID", "Product Name", "Current Stock", "Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblInventory.setRowHeight(35);
        jScrollPane1.setViewportView(tblInventory);

        cardContainer.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 940, 490));

        add(cardContainer, new java.awt.GridBagConstraints());
    }// </editor-fold>//GEN-END:initComponents

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        int selectedRow = tblInventory.getSelectedRow();

        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Please select a product from the table first.", "No Selection", JOptionPane.WARNING_MESSAGE);
            return;
        }

        Object idObj = tblInventory.getValueAt(selectedRow, 0);
        Object nameObj = tblInventory.getValueAt(selectedRow, 1);
        Object stockObj = tblInventory.getValueAt(selectedRow, 2);

        if (idObj == null || nameObj == null || stockObj == null) {
            JOptionPane.showMessageDialog(this, "This row contains empty or invalid data.", "Data Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        int productId = Integer.parseInt(idObj.toString());
        String productName = nameObj.toString();
        int currentStock = Integer.parseInt(stockObj.toString());

        java.awt.Window parentWindow = javax.swing.SwingUtilities.getWindowAncestor(this);
        java.awt.Frame parentFrame = (parentWindow instanceof java.awt.Frame) ? (java.awt.Frame) parentWindow : null;

        ui.dialogs.UpdateStockDialog dialog = new ui.dialogs.UpdateStockDialog(parentFrame, true, productId, productName, currentStock);
        dialog.setLocationRelativeTo(parentFrame);
        dialog.setVisible(true);

        loadInventoryToTable();
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void ExportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExportActionPerformed
        if (tblInventory.getRowCount() == 0) {
            JOptionPane.showMessageDialog(this, "There is no data to export!", "Export Error", JOptionPane.WARNING_MESSAGE);
            return;
        }

        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setDialogTitle("Export to CSV");
        fileChooser.setSelectedFile(new java.io.File("SalesReport.csv"));

        int userSelection = fileChooser.showSaveDialog(this);

        if (userSelection == JFileChooser.APPROVE_OPTION) {
            java.io.File fileToSave = fileChooser.getSelectedFile();

            try (java.io.FileWriter fw = new java.io.FileWriter(fileToSave); java.io.BufferedWriter bw = new java.io.BufferedWriter(fw)) {

                for (int i = 0; i < tblInventory.getColumnCount(); i++) {
                    bw.write(tblInventory.getColumnName(i) + ",");
                }
                bw.newLine();

                for (int i = 0; i < tblInventory.getRowCount(); i++) {
                    for (int j = 0; j < tblInventory.getColumnCount(); j++) {
                        Object cellValue = tblInventory.getValueAt(i, j);

                        if (cellValue != null) {
                            bw.write(cellValue.toString().replace(",", "") + ",");
                        } else {
                            bw.write(",");
                        }
                    }
                    bw.newLine();
                }

                JOptionPane.showMessageDialog(this, "Data successfully exported to:\n" + fileToSave.getAbsolutePath(), "Export Success", JOptionPane.INFORMATION_MESSAGE);

            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Error exporting file: " + e.getMessage(), "Export Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_ExportActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Export;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JPanel cardContainer;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblInventory;
    // End of variables declaration//GEN-END:variables
}
