package ui.menuPanel;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.SwingConstants;
import ui.dialogs.AddProductDialog;
import ui.auth.LoginPanel;

public class ProductsPanel extends javax.swing.JPanel {

    private int productId;

    public ProductsPanel() {
        initComponents();
        loadProducts("");

        tblProducts.getTableHeader().setFont(
                new java.awt.Font("Geist SemiBold", java.awt.Font.PLAIN, 11)
        );
        tblProducts.getTableHeader().setBackground(
                new java.awt.Color(245, 245, 245)
        );
        tblProducts.getTableHeader().setForeground(
                new java.awt.Color(80, 80, 80)
        );
        tblProducts.setIntercellSpacing(new java.awt.Dimension(0, 0));
        tblProducts.setShowGrid(false);

        DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
        centerRenderer.setHorizontalAlignment(SwingConstants.CENTER);

        for (int i = 0; i < tblProducts.getColumnCount(); i++) {
            tblProducts.getColumnModel().getColumn(i).setCellRenderer(centerRenderer);
        }
    }

    public void loadProducts(String searchQuery) {
        boolean showArchived = chkShowArchived.isSelected();
        String sql;

        if (showArchived) {
            sql = "SELECT p.product_id, p.name AS product_name, c.category_name, p.price, ISNULL(i.current_stock, 0) AS current_stock "
                    + "FROM Products p "
                    + "JOIN Categories c ON p.category_id = c.category_id "
                    + "LEFT JOIN Inventory i ON p.product_id = i.product_id "
                    + "WHERE p.is_archived = 1 AND (p.name LIKE ? OR c.category_name LIKE ?) "
                    + "ORDER BY p.name ASC";
        } else {
            sql = "SELECT product_id, product_name, category_name, price, current_stock "
                    + "FROM vw_ProductList "
                    + "WHERE product_name LIKE ? OR category_name LIKE ? "
                    + "ORDER BY product_name ASC";
        }

        try (java.sql.Connection conn = database.DBConnection.getConnection(); java.sql.PreparedStatement pstmt = conn.prepareStatement(sql)) {

            String searchParam = "%" + searchQuery.trim() + "%";
            pstmt.setString(1, searchParam);
            pstmt.setString(2, searchParam);

            try (java.sql.ResultSet rs = pstmt.executeQuery()) {
                javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) tblProducts.getModel();
                model.setRowCount(0);

                while (rs.next()) {
                    model.addRow(new Object[]{
                        rs.getInt("product_id"),
                        rs.getString("product_name"),
                        rs.getString("category_name"),
                        rs.getDouble("price"),
                    });
                }
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        cardContainer = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnAdd = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnArchive = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblProducts = new javax.swing.JTable();
        chkShowArchived = new javax.swing.JCheckBox();

        setBackground(new java.awt.Color(248, 250, 252));
        setBorder(javax.swing.BorderFactory.createEmptyBorder(30, 25, 30, 25));
        setPreferredSize(new java.awt.Dimension(1042, 610));
        setLayout(new java.awt.GridBagLayout());

        cardContainer.setBackground(new java.awt.Color(255, 255, 255));
        cardContainer.setMaximumSize(new java.awt.Dimension(980, 610));
        cardContainer.setMinimumSize(new java.awt.Dimension(980, 610));
        cardContainer.setPreferredSize(new java.awt.Dimension(980, 610));
        cardContainer.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(226, 232, 240)));

        jLabel1.setFont(new java.awt.Font("Georgia", 1, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(15, 23, 42));
        jLabel1.setText("Manage Menu Products");

        btnAdd.setBackground(new java.awt.Color(227, 83, 10));
        btnAdd.setFont(new java.awt.Font("Geist SemiBold", 0, 12)); // NOI18N
        btnAdd.setForeground(new java.awt.Color(255, 255, 255));
        btnAdd.setText("Add Product");
        btnAdd.setPreferredSize(new java.awt.Dimension(120, 35));
        btnAdd.addActionListener(this::btnAddActionPerformed);

        btnUpdate.setBackground(new java.awt.Color(241, 245, 249));
        btnUpdate.setFont(new java.awt.Font("Geist SemiBold", 0, 12)); // NOI18N
        btnUpdate.setText("Edit");
        btnUpdate.setPreferredSize(new java.awt.Dimension(100, 35));
        btnUpdate.addActionListener(this::btnUpdateActionPerformed);

        btnArchive.setBackground(new java.awt.Color(254, 226, 226));
        btnArchive.setFont(new java.awt.Font("Geist SemiBold", 0, 12)); // NOI18N
        btnArchive.setForeground(new java.awt.Color(153, 27, 27));
        btnArchive.setText("Archived");
        btnArchive.setPreferredSize(new java.awt.Dimension(100, 35));
        btnArchive.addActionListener(this::btnArchiveActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 423, Short.MAX_VALUE)
                .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnArchive, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnArchive, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        cardContainer.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 980, 70));

        jScrollPane2.setPreferredSize(new java.awt.Dimension(930, 400));

        tblProducts.setFont(new java.awt.Font("Geist", 0, 12)); // NOI18N
        tblProducts.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Product Name", "Category", "Price"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblProducts.setRowHeight(35);
        jScrollPane2.setViewportView(tblProducts);

        cardContainer.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, 470));

        chkShowArchived.setFont(new java.awt.Font("Geist SemiBold", 0, 10)); // NOI18N
        chkShowArchived.setText("Show Archived");
        chkShowArchived.addActionListener(this::chkShowArchivedActionPerformed);
        cardContainer.add(chkShowArchived, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 100, -1));

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(36, 31, 36, 31);
        add(cardContainer, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        java.awt.Window parentWindow = javax.swing.SwingUtilities.getWindowAncestor(this);
        java.awt.Frame parentFrame = (parentWindow instanceof java.awt.Frame) ? (java.awt.Frame) parentWindow : null;

        AddProductDialog dialog = new AddProductDialog(parentFrame, true);
        dialog.setLocationRelativeTo(parentFrame);
        dialog.setVisible(true);

        loadProducts("");
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnArchiveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnArchiveActionPerformed
        int selectedRow = tblProducts.getSelectedRow();
        if (selectedRow == -1) {
            javax.swing.JOptionPane.showMessageDialog(this, "Please select a product first.");
            return;
        }

        int productId = (int) tblProducts.getValueAt(selectedRow, 0);
        String productName = (String) tblProducts.getValueAt(selectedRow, 1);

        boolean isArchivedView = chkShowArchived.isSelected();
        String actionWord = isArchivedView ? "restore" : "archive";
        String logAction = isArchivedView ? "RESTORE_PRODUCT" : "ARCHIVE_PRODUCT";
        int newArchiveStatus = isArchivedView ? 0 : 1;

        int confirm = javax.swing.JOptionPane.showConfirmDialog(this,
                "Are you sure you want to " + actionWord + " '" + productName + "'?",
                "Confirm Action",
                javax.swing.JOptionPane.YES_NO_OPTION);

        if (confirm == javax.swing.JOptionPane.YES_OPTION) {
            try (java.sql.Connection conn = database.DBConnection.getConnection()) {

                String sql = "UPDATE Products SET is_archived = ? WHERE product_id = ?";
                try (java.sql.PreparedStatement pstmt = conn.prepareStatement(sql)) {
                    pstmt.setInt(1, newArchiveStatus);
                    pstmt.setInt(2, productId);
                    pstmt.executeUpdate();
                }

                String logSql = "{call sp_InsertAuditLog(?, ?, ?)}";
                try (java.sql.CallableStatement cstmtLog = conn.prepareCall(logSql)) {
                    cstmtLog.setInt(1, LoginPanel.loggedInUserId);
                    cstmtLog.setString(2, logAction);
                    cstmtLog.setString(3, actionWord.substring(0, 1).toUpperCase() + actionWord.substring(1) + "d Product ID: " + productId);
                    cstmtLog.execute();
                }

                javax.swing.JOptionPane.showMessageDialog(this, "Product " + actionWord + "d successfully.");

                loadProducts("");

            } catch (Exception e) {
                e.printStackTrace();
                javax.swing.JOptionPane.showMessageDialog(this, "Error processing request: " + e.getMessage());
            }
        }
    }//GEN-LAST:event_btnArchiveActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        int selectedRow = tblProducts.getSelectedRow();

        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Please select a product to edit first.", "No Selection", JOptionPane.WARNING_MESSAGE);
            return;
        }

        int id = (int) tblProducts.getValueAt(selectedRow, 0);
        String name = (String) tblProducts.getValueAt(selectedRow, 1);
        String category = (String) tblProducts.getValueAt(selectedRow, 2);
        double price = (double) tblProducts.getValueAt(selectedRow, 3);

        java.awt.Window parentWindow = javax.swing.SwingUtilities.getWindowAncestor(this);
        java.awt.Frame parentFrame = (parentWindow instanceof java.awt.Frame) ? (java.awt.Frame) parentWindow : null;

        ui.dialogs.EditProductDialog dialog = new ui.dialogs.EditProductDialog(parentFrame, true, id, name, category, price);
        dialog.setLocationRelativeTo(parentFrame);
        dialog.setVisible(true);

        loadProducts("");
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void chkShowArchivedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkShowArchivedActionPerformed
        if (chkShowArchived.isSelected()) {
            btnArchive.setText("Restore");
        } else {
            btnArchive.setText("Archive");
        }

        loadProducts("");
    }//GEN-LAST:event_chkShowArchivedActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnArchive;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JPanel cardContainer;
    private javax.swing.JCheckBox chkShowArchived;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblProducts;
    // End of variables declaration//GEN-END:variables
}
