package ui.menuPanel;

import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import ui.auth.LoginPanel;

public class PurchasesPanel extends javax.swing.JPanel {

    public PurchasesPanel() {
        initComponents();

        tblPurchases.getTableHeader().setFont(
                new java.awt.Font("Geist SemiBold", java.awt.Font.PLAIN, 10)
        );
        tblPurchases.getTableHeader().setBackground(
                new java.awt.Color(245, 245, 245)
        );
        tblPurchases.getTableHeader().setForeground(
                new java.awt.Color(80, 80, 80)
        );
        tblPurchases.setIntercellSpacing(new java.awt.Dimension(0, 0));
        tblPurchases.setShowGrid(false);
        
        DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
        centerRenderer.setHorizontalAlignment(SwingConstants.CENTER);

        for (int i = 0; i < tblPurchases.getColumnCount(); i++) {
            tblPurchases.getColumnModel().getColumn(i).setCellRenderer(centerRenderer);
        }

        loadPurchases();
    }

    public void loadPurchases() {
        String sql = "SELECT p.purchase_id, p.purchase_date, s.supplier_name, "
                + "(pd.quantity_bought * pd.cost_price) AS total_cost, p.status, prod.name AS product_name "
                + "FROM Purchases p "
                + "JOIN Suppliers s ON p.supplier_id = s.supplier_id "
                + "JOIN Purchase_Details pd ON p.purchase_id = pd.purchase_id "
                + "JOIN Products prod ON pd.product_id = prod.product_id "
                + "ORDER BY p.purchase_id DESC";

        try (java.sql.Connection conn = database.DBConnection.getConnection(); java.sql.PreparedStatement pstmt = conn.prepareStatement(sql); java.sql.ResultSet rs = pstmt.executeQuery()) {

            javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) tblPurchases.getModel();
            model.setRowCount(0);

            java.text.SimpleDateFormat sdf = new java.text.SimpleDateFormat("MMM dd, yyyy");

            while (rs.next()) {
                model.addRow(new Object[]{
                    rs.getInt("purchase_id"),
                    sdf.format(rs.getTimestamp("purchase_date")),
                    rs.getString("supplier_name"),
                    rs.getDouble("total_cost"),
                    rs.getString("status"),
                    rs.getString("product_name")
                });
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cardContainer = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnNewPurchase = new javax.swing.JButton();
        btnVoid = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPurchases = new javax.swing.JTable();

        setBackground(new java.awt.Color(248, 250, 252));
        setLayout(new java.awt.GridBagLayout());

        cardContainer.setBackground(new java.awt.Color(255, 255, 255));
        cardContainer.setMaximumSize(new java.awt.Dimension(980, 610));
        cardContainer.setMinimumSize(new java.awt.Dimension(980, 610));
        cardContainer.setPreferredSize(new java.awt.Dimension(980, 610));
        cardContainer.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(226, 232, 240)));

        jLabel1.setFont(new java.awt.Font("Georgia", 1, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(15, 23, 42));
        jLabel1.setText("Purchase Orders");

        btnNewPurchase.setBackground(new java.awt.Color(231, 90, 14));
        btnNewPurchase.setFont(new java.awt.Font("Geist SemiBold", 0, 12)); // NOI18N
        btnNewPurchase.setForeground(new java.awt.Color(255, 255, 255));
        btnNewPurchase.setText("Add Purchase");
        btnNewPurchase.setPreferredSize(new java.awt.Dimension(113, 30));
        btnNewPurchase.addActionListener(this::btnNewPurchaseActionPerformed);

        btnVoid.setBackground(new java.awt.Color(254, 226, 226));
        btnVoid.setFont(new java.awt.Font("Geist SemiBold", 0, 12)); // NOI18N
        btnVoid.setForeground(new java.awt.Color(153, 27, 27));
        btnVoid.setText("Void");
        btnVoid.setPreferredSize(new java.awt.Dimension(113, 30));
        btnVoid.addActionListener(this::btnVoidActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 583, Short.MAX_VALUE)
                .addComponent(btnNewPurchase, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnVoid, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnNewPurchase, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnVoid, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        cardContainer.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 980, 70));

        tblPurchases.setFont(new java.awt.Font("Geist", 0, 12)); // NOI18N
        tblPurchases.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Purchase ID", "Date", "Supplier", "Total Cost", "Status", "Product"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblPurchases.setRowHeight(35);
        jScrollPane1.setViewportView(tblPurchases);

        cardContainer.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 940, 500));

        add(cardContainer, new java.awt.GridBagConstraints());
    }// </editor-fold>//GEN-END:initComponents

    private void btnNewPurchaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewPurchaseActionPerformed
        java.awt.Window parentWindow = javax.swing.SwingUtilities.getWindowAncestor(this);
        java.awt.Frame parentFrame = (parentWindow instanceof java.awt.Frame) ? (java.awt.Frame) parentWindow : null;

        ui.dialogs.AddPurchaseDialog dialog = new ui.dialogs.AddPurchaseDialog(parentFrame, true);
        dialog.setLocationRelativeTo(parentFrame);
        dialog.setVisible(true);

        loadPurchases();
    }//GEN-LAST:event_btnNewPurchaseActionPerformed

    private void btnVoidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoidActionPerformed
        int selectedRow = tblPurchases.getSelectedRow();

        if (selectedRow == -1) {
            javax.swing.JOptionPane.showMessageDialog(this, "Please select a purchase order to void.", "No Selection", javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }

        int purchaseId = (int) tblPurchases.getValueAt(selectedRow, 0);
        String currentStatus = (String) tblPurchases.getValueAt(selectedRow, 4);

        if ("Pending".equalsIgnoreCase(currentStatus)) {
            javax.swing.JOptionPane.showMessageDialog(this, "This purchase is already marked as Cancelled.", "Already Cancelled", javax.swing.JOptionPane.INFORMATION_MESSAGE);
            return;
        }

        int confirm = javax.swing.JOptionPane.showConfirmDialog(this,
                "Are you sure you want to cancel Purchase #" + purchaseId + "?\nThis will remove the items from the kitchen inventory.",
                "Confirm Void", javax.swing.JOptionPane.YES_NO_OPTION, javax.swing.JOptionPane.WARNING_MESSAGE);

        if (confirm != javax.swing.JOptionPane.YES_OPTION) {
            return;
        }

        java.sql.Connection conn = null;
        try {
            conn = database.DBConnection.getConnection();
            conn.setAutoCommit(false);

            String sqlVoid = "UPDATE Purchases SET status = 'Pending' WHERE purchase_id = ?";
            try (java.sql.PreparedStatement pstmtVoid = conn.prepareStatement(sqlVoid)) {
                pstmtVoid.setInt(1, purchaseId);
                pstmtVoid.executeUpdate();
            }

            String sqlGetItems = "SELECT product_id, quantity_bought FROM Purchase_Details WHERE purchase_id = ?";
            String sqlRemove = "UPDATE Inventory SET current_stock = current_stock - ? WHERE product_id = ?";

            try (java.sql.PreparedStatement pstmtGetItems = conn.prepareStatement(sqlGetItems); java.sql.PreparedStatement pstmtRemove = conn.prepareStatement(sqlRemove)) {

                pstmtGetItems.setInt(1, purchaseId);
                try (java.sql.ResultSet rsItems = pstmtGetItems.executeQuery()) {
                    while (rsItems.next()) {
                        int productId = rsItems.getInt("product_id");
                        int qtyToRemove = rsItems.getInt("quantity_bought");

                        pstmtRemove.setInt(1, qtyToRemove);
                        pstmtRemove.setInt(2, productId);
                        pstmtRemove.addBatch();
                    }
                }
                pstmtRemove.executeBatch();
            }

            String sqlLog = "INSERT INTO AuditLogs (user_id, action, description) VALUES (?, 'VOID_PURCHASE', ?)";
            try (java.sql.PreparedStatement pstmtLog = conn.prepareStatement(sqlLog)) {
                pstmtLog.setInt(1, LoginPanel.loggedInUserId);
                pstmtLog.setString(2, "Cancelled Purchase ID: " + purchaseId + " and removed stock.");
                pstmtLog.executeUpdate();
            }

            conn.commit();

            javax.swing.JOptionPane.showMessageDialog(this, "Purchase #" + purchaseId + " successfully cancelled.\nInventory has been deducted.", "Void Successful", javax.swing.JOptionPane.INFORMATION_MESSAGE);

            loadPurchases();

        } catch (Exception e) {
            try {
                if (conn != null) {
                    conn.rollback();
                }
            } catch (Exception ex) {
            }

            String errorMsg = e.getMessage();
            if (errorMsg != null && errorMsg.contains("constraint") && errorMsg.contains("current_stock")) {
                javax.swing.JOptionPane.showMessageDialog(this,
                        "Void Failed: Items Already Sold!\n\nYou cannot cancel this purchase because the kitchen has already sold some of these items. Voiding it would cause negative stock.",
                        "Inventory Protection",
                        javax.swing.JOptionPane.ERROR_MESSAGE);
            } else {
                e.printStackTrace();
                javax.swing.JOptionPane.showMessageDialog(this, "Error voiding purchase: " + errorMsg, "Database Error", javax.swing.JOptionPane.ERROR_MESSAGE);
            }
        } finally {
            if (conn != null) {
                try {
                    conn.setAutoCommit(true);
                } catch (Exception ex) {
                }
                try {
                    conn.close();
                } catch (Exception ex) {
                }
            }
        }
    }//GEN-LAST:event_btnVoidActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnNewPurchase;
    private javax.swing.JButton btnVoid;
    private javax.swing.JPanel cardContainer;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblPurchases;
    // End of variables declaration//GEN-END:variables
}
