package ui.menuPanel;

// Imports Swing constants for table alignment
import javax.swing.SwingConstants;

// Imports table cell renderer
import javax.swing.table.DefaultTableCellRenderer;

// Imports LoginPanel to get logged-in user ID
import ui.auth.LoginPanel;

public class PurchasesPanel extends javax.swing.JPanel {

    // Constructor
    // Runs when PurchasesPanel is created
    public PurchasesPanel() {

        // Initializes all UI components
        initComponents();

        // Styles the table header font
        tblPurchases.getTableHeader().setFont(
                new java.awt.Font(
                        "Geist SemiBold",
                        java.awt.Font.PLAIN,
                        10
                )
        );

        // Changes table header background color
        tblPurchases.getTableHeader().setBackground(
                new java.awt.Color(245, 245, 245)
        );

        // Changes table header text color
        tblPurchases.getTableHeader().setForeground(
                new java.awt.Color(80, 80, 80)
        );

        // Removes spacing between table cells
        tblPurchases.setIntercellSpacing(
                new java.awt.Dimension(0, 0)
        );

        // Removes table grid lines
        tblPurchases.setShowGrid(false);

        // Creates center alignment renderer
        DefaultTableCellRenderer centerRenderer
                = new DefaultTableCellRenderer();

        // Centers text horizontally
        centerRenderer.setHorizontalAlignment(
                SwingConstants.CENTER
        );

        // Applies center alignment to all columns
        for (int i = 0; i < tblPurchases.getColumnCount(); i++) {

            tblPurchases.getColumnModel()
                    .getColumn(i)
                    .setCellRenderer(centerRenderer);
        }

        // Loads purchase records into table
        loadPurchases();
    }

    // Loads purchase records from database
    public void loadPurchases() {

        // SQL query:
        // Gets purchase order information
        String sql
                = "SELECT p.purchase_id, "
                + "p.purchase_date, "
                + "s.supplier_name, "
                + "(pd.quantity_bought * pd.cost_price) "
                + "AS total_cost, "
                + "p.status, "
                + "prod.name AS product_name "
                + "FROM Purchases p "
                + "JOIN Suppliers s "
                + "ON p.supplier_id = s.supplier_id "
                + "JOIN Purchase_Details pd "
                + "ON p.purchase_id = pd.purchase_id "
                + "JOIN Products prod "
                + "ON pd.product_id = prod.product_id "
                + "ORDER BY p.purchase_id DESC";

        try (

                // Connects to database
                java.sql.Connection conn
                = database.DBConnection.getConnection();

                // Creates PreparedStatement
                java.sql.PreparedStatement pstmt
                = conn.prepareStatement(sql);

                // Executes SELECT query
                java.sql.ResultSet rs
                = pstmt.executeQuery()
        ) {

            // Gets table model
            javax.swing.table.DefaultTableModel model
                    = (javax.swing.table.DefaultTableModel)
                            tblPurchases.getModel();

            // Clears existing rows
            model.setRowCount(0);

            // Date format for purchase date
            java.text.SimpleDateFormat sdf
                    = new java.text.SimpleDateFormat(
                            "MMM dd, yyyy"
                    );

            // Loops through purchase records
            while (rs.next()) {

                // Adds row into table
                model.addRow(new Object[]{
                    rs.getInt("purchase_id"),

                    // Formats purchase date
                    sdf.format(
                            rs.getTimestamp("purchase_date")
                    ),

                    rs.getString("supplier_name"),
                    rs.getDouble("total_cost"),
                    rs.getString("status"),
                    rs.getString("product_name")
                });
            }

        } catch (Exception e) {

            // Prints error in console
            e.printStackTrace();
        }
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cardContainer = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnNewPurchase = new javax.swing.JButton();
        btnVoid = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPurchases = new javax.swing.JTable();

        setBackground(new java.awt.Color(248, 250, 252));
        setLayout(new java.awt.GridBagLayout());

        cardContainer.setBackground(new java.awt.Color(255, 255, 255));
        cardContainer.setMaximumSize(new java.awt.Dimension(980, 610));
        cardContainer.setMinimumSize(new java.awt.Dimension(980, 610));
        cardContainer.setPreferredSize(new java.awt.Dimension(980, 610));
        cardContainer.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(226, 232, 240)));

        jLabel1.setFont(new java.awt.Font("Georgia", 1, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(15, 23, 42));
        jLabel1.setText("Purchase Orders");

        btnNewPurchase.setBackground(new java.awt.Color(231, 90, 14));
        btnNewPurchase.setFont(new java.awt.Font("Geist SemiBold", 0, 12)); // NOI18N
        btnNewPurchase.setForeground(new java.awt.Color(255, 255, 255));
        btnNewPurchase.setText("Add Purchase");
        btnNewPurchase.setPreferredSize(new java.awt.Dimension(113, 30));
        btnNewPurchase.addActionListener(this::btnNewPurchaseActionPerformed);

        btnVoid.setBackground(new java.awt.Color(254, 226, 226));
        btnVoid.setFont(new java.awt.Font("Geist SemiBold", 0, 12)); // NOI18N
        btnVoid.setForeground(new java.awt.Color(153, 27, 27));
        btnVoid.setText("Update Status");
        btnVoid.setPreferredSize(new java.awt.Dimension(113, 30));
        btnVoid.addActionListener(this::btnVoidActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 532, Short.MAX_VALUE)
                .addComponent(btnNewPurchase, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnVoid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnNewPurchase, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnVoid, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        cardContainer.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 980, 70));

        tblPurchases.setFont(new java.awt.Font("Geist", 0, 12)); // NOI18N
        tblPurchases.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Purchase ID", "Date", "Supplier", "Total Cost", "Status", "Product"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblPurchases.setRowHeight(35);
        jScrollPane1.setViewportView(tblPurchases);

        cardContainer.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 940, 500));

        add(cardContainer, new java.awt.GridBagConstraints());
    }// </editor-fold>//GEN-END:initComponents

    private void btnNewPurchaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewPurchaseActionPerformed
        // Gets current window
        java.awt.Window parentWindow
                = javax.swing.SwingUtilities
                        .getWindowAncestor(this);

        // Converts window into Frame
        java.awt.Frame parentFrame
                = (parentWindow instanceof java.awt.Frame)
                ? (java.awt.Frame) parentWindow
                : null;

        // Opens AddPurchaseDialog
        ui.dialogs.AddPurchaseDialog dialog
                = new ui.dialogs.AddPurchaseDialog(
                        parentFrame,
                        true
                );

        // Centers dialog relative to parent frame
        dialog.setLocationRelativeTo(parentFrame);

        // Displays dialog
        dialog.setVisible(true);

        // Reloads updated purchase records
        loadPurchases();
    }//GEN-LAST:event_btnNewPurchaseActionPerformed

    private void btnVoidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoidActionPerformed
        // Gets selected row from table
        int selectedRow
                = tblPurchases.getSelectedRow();

        // Validation:
        // Checks if user selected a row
        if (selectedRow == -1) {

            javax.swing.JOptionPane.showMessageDialog(
                    this,
                    "Please select a purchase order to update.",
                    "No Selection",
                    javax.swing.JOptionPane.WARNING_MESSAGE
            );

            return;
        }

        // Gets selected purchase ID
        int purchaseId
                = (int) tblPurchases.getValueAt(
                        selectedRow,
                        0
                );

        // Gets current purchase status
        String currentStatus
                = (String) tblPurchases.getValueAt(
                        selectedRow,
                        4
                );

        // Checks if current status is Pending
        boolean isCurrentlyPending
                = "Pending".equalsIgnoreCase(currentStatus);

        // Determines new status
        String newStatus
                = isCurrentlyPending
                ? "Delivered"
                : "Pending";

        // Determines action description
        String actionWord
                = isCurrentlyPending
                ? "mark as Delivered"
                : "revert to Pending";

        // Determines stock action description
        String stockAction
                = isCurrentlyPending
                ? "add the items to"
                : "remove the items from";

        // Determines math operator
        // "+" adds stock
        // "-" subtracts stock
        String mathOperator
                = isCurrentlyPending
                ? "+"
                : "-";

        // Confirmation dialog
        int confirm
                = javax.swing.JOptionPane.showConfirmDialog(
                        this,
                        "Are you sure you want to "
                        + actionWord
                        + " Purchase #"
                        + purchaseId
                        + "?\nThis will "
                        + stockAction
                        + " the kitchen inventory.",
                        "Confirm Status Update",
                        javax.swing.JOptionPane.YES_NO_OPTION,
                        javax.swing.JOptionPane.WARNING_MESSAGE
                );

        // Stops process if user clicks NO
        if (confirm
                != javax.swing.JOptionPane.YES_OPTION) {

            return;
        }

        java.sql.Connection conn = null;

        try {

            // Connects to database
            conn = database.DBConnection.getConnection();

            // Starts transaction mode
            // All queries must succeed together
            conn.setAutoCommit(false);

            // ================= PURCHASE STATUS UPDATE =================

            // SQL query:
            // Updates purchase status
            String sqlStatus
                    = "UPDATE Purchases "
                    + "SET status = ? "
                    + "WHERE purchase_id = ?";

            try (

                    // Creates PreparedStatement
                    java.sql.PreparedStatement pstmtStatus
                    = conn.prepareStatement(sqlStatus)
            ) {

                // Updates purchase status
                pstmtStatus.setString(1, newStatus);

                // Selects correct purchase order
                pstmtStatus.setInt(2, purchaseId);

                // Executes UPDATE query
                pstmtStatus.executeUpdate();
            }

            // ================= INVENTORY UPDATE =================

            // SQL query:
            // Gets purchased items
            String sqlGetItems
                    = "SELECT product_id, quantity_bought "
                    + "FROM Purchase_Details "
                    + "WHERE purchase_id = ?";

            // SQL query:
            // Updates inventory stock
            String sqlInventory
                    = "UPDATE Inventory "
                    + "SET current_stock = current_stock "
                    + mathOperator
                    + " ? "
                    + "WHERE product_id = ?";

            try (

                    // Creates PreparedStatement
                    java.sql.PreparedStatement pstmtGetItems
                    = conn.prepareStatement(sqlGetItems);

                    java.sql.PreparedStatement pstmtInv
                    = conn.prepareStatement(sqlInventory)
            ) {

                // Selects correct purchase order
                pstmtGetItems.setInt(1, purchaseId);

                try (

                        // Executes SELECT query
                        java.sql.ResultSet rsItems
                        = pstmtGetItems.executeQuery()
                ) {

                    // Loops through purchased items
                    while (rsItems.next()) {

                        // Gets product ID
                        int productId
                                = rsItems.getInt("product_id");

                        // Gets purchased quantity
                        int qty
                                = rsItems.getInt("quantity_bought");

                        // Adds or subtracts stock
                        pstmtInv.setInt(1, qty);

                        // Selects correct product
                        pstmtInv.setInt(2, productId);

                        // Adds query into batch
                        pstmtInv.addBatch();
                    }
                }

                // Executes all inventory updates together
                pstmtInv.executeBatch();
            }

            // ================= AUDIT LOG =================

            // Creates audit description
            String logDesc
                    = isCurrentlyPending
                    ? "Marked Purchase ID: "
                    + purchaseId
                    + " as Delivered and added stock."

                    : "Reverted Purchase ID: "
                    + purchaseId
                    + " to Pending and removed stock.";

            // SQL query:
            // Inserts audit log record
            String sqlLog
                    = "INSERT INTO AuditLogs "
                    + "(user_id, action, description) "
                    + "VALUES (?, 'UPDATE_PURCHASE', ?)";

            try (

                    // Creates PreparedStatement
                    java.sql.PreparedStatement pstmtLog
                    = conn.prepareStatement(sqlLog)
            ) {

                // Inserts logged-in user ID
                pstmtLog.setInt(
                        1,
                        LoginPanel.loggedInUserId
                );

                // Inserts audit description
                pstmtLog.setString(2, logDesc);

                // Executes INSERT query
                pstmtLog.executeUpdate();
            }

            // Saves all database changes permanently
            conn.commit();

            // Success message
            javax.swing.JOptionPane.showMessageDialog(
                    this,
                    "Purchase #"
                    + purchaseId
                    + " successfully updated to "
                    + newStatus
                    + ".",
                    "Status Updated",
                    javax.swing.JOptionPane.INFORMATION_MESSAGE
            );

            // Reloads updated purchase records
            loadPurchases();

        } catch (Exception e) {

            try {

                // Cancels all database changes if an error happens
                if (conn != null) {

                    conn.rollback();
                }

            } catch (Exception ex) {

            }

            // Gets error message
            String errorMsg = e.getMessage();

            // Handles stock constraint errors
            if (errorMsg != null
                    && errorMsg.contains("constraint")
                    && errorMsg.contains("current_stock")) {

                javax.swing.JOptionPane.showMessageDialog(
                        this,
                        "Update Failed: Items Already Sold!\n\n"
                        + "You cannot revert this purchase to Pending "
                        + "because the kitchen has already sold "
                        + "some of these items. "
                        + "Reverting it would cause negative stock.",
                        "Inventory Protection",
                        javax.swing.JOptionPane.ERROR_MESSAGE
                );

            } else {

                // Prints error in console
                e.printStackTrace();

                // Shows database/system error
                javax.swing.JOptionPane.showMessageDialog(
                        this,
                        "Error updating purchase: "
                        + errorMsg,
                        "Database Error",
                        javax.swing.JOptionPane.ERROR_MESSAGE
                );
            }

        } finally {

            if (conn != null) {

                try {

                    // Turns auto-commit back on
                    conn.setAutoCommit(true);

                } catch (Exception ex) {

                }

                try {

                    // Closes database connection
                    conn.close();

                } catch (Exception ex) {

                }
            }
        }
    }//GEN-LAST:event_btnVoidActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnNewPurchase;
    private javax.swing.JButton btnVoid;
    private javax.swing.JPanel cardContainer;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblPurchases;
    // End of variables declaration//GEN-END:variables
}
