package ui.menuPanel;

import ui.auth.LoginPanel;

public class SuppliersPanel extends javax.swing.JPanel {

    public SuppliersPanel() {
        initComponents();
        
        tblSuppliers.getTableHeader().setFont(
                new java.awt.Font("Geist SemiBold", java.awt.Font.PLAIN, 10)
        );
        tblSuppliers.getTableHeader().setBackground(
                new java.awt.Color(245, 245, 245)
        );
        tblSuppliers.getTableHeader().setForeground(
                new java.awt.Color(80, 80, 80)
        );
        tblSuppliers.setIntercellSpacing(new java.awt.Dimension(0, 0));
        tblSuppliers.setShowGrid(false);
        
        loadSuppliers("");
    }
    
    public void loadSuppliers(String searchQuery) {
        try {
            java.sql.Connection conn = database.DBConnection.getConnection();
            
            String sql = "SELECT supplier_id, supplier_name, contact_no, address " +
                         "FROM Suppliers " +
                         "WHERE is_archived = 0 AND (supplier_name LIKE ? OR address LIKE ?) " +
                         "ORDER BY supplier_name ASC";
                         
            java.sql.PreparedStatement pstmt = conn.prepareStatement(sql);
            String searchParam = "%" + searchQuery.trim() + "%";
            pstmt.setString(1, searchParam);
            pstmt.setString(2, searchParam);
            
            java.sql.ResultSet rs = pstmt.executeQuery();
            javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) tblSuppliers.getModel();
            model.setRowCount(0); 

            while (rs.next()) {
                model.addRow(new Object[]{
                    rs.getInt("supplier_id"),
                    rs.getString("supplier_name"),
                    rs.getString("address"),      
                    rs.getString("contact_no")
                });
            }
        } catch (Exception e) {
            e.printStackTrace();
            javax.swing.JOptionPane.showMessageDialog(this, "Error loading suppliers: " + e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cardContainer = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnAddSupplier = new javax.swing.JButton();
        btnEditSupplier = new javax.swing.JButton();
        btnDeleteSupplier = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblSuppliers = new javax.swing.JTable();

        setBackground(new java.awt.Color(248, 250, 252));
        setLayout(new java.awt.GridBagLayout());

        cardContainer.setBackground(new java.awt.Color(255, 255, 255));
        cardContainer.setMaximumSize(new java.awt.Dimension(980, 610));
        cardContainer.setMinimumSize(new java.awt.Dimension(980, 610));
        cardContainer.setPreferredSize(new java.awt.Dimension(980, 610));
        cardContainer.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(226, 232, 240)));

        jLabel1.setFont(new java.awt.Font("Georgia", 1, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(15, 23, 42));
        jLabel1.setText("Manage Suppliers");

        btnAddSupplier.setBackground(new java.awt.Color(227, 83, 10));
        btnAddSupplier.setFont(new java.awt.Font("Geist SemiBold", 0, 12)); // NOI18N
        btnAddSupplier.setForeground(new java.awt.Color(255, 255, 255));
        btnAddSupplier.setText("Add");
        btnAddSupplier.setPreferredSize(new java.awt.Dimension(100, 35));
        btnAddSupplier.addActionListener(this::btnAddSupplierActionPerformed);

        btnEditSupplier.setBackground(new java.awt.Color(241, 245, 249));
        btnEditSupplier.setFont(new java.awt.Font("Geist SemiBold", 0, 12)); // NOI18N
        btnEditSupplier.setText("Edit");
        btnEditSupplier.setPreferredSize(new java.awt.Dimension(100, 35));
        btnEditSupplier.addActionListener(this::btnEditSupplierActionPerformed);

        btnDeleteSupplier.setBackground(new java.awt.Color(254, 226, 226));
        btnDeleteSupplier.setFont(new java.awt.Font("Geist SemiBold", 0, 12)); // NOI18N
        btnDeleteSupplier.setForeground(new java.awt.Color(153, 27, 27));
        btnDeleteSupplier.setText("Archived");
        btnDeleteSupplier.setPreferredSize(new java.awt.Dimension(100, 35));
        btnDeleteSupplier.addActionListener(this::btnDeleteSupplierActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 493, Short.MAX_VALUE)
                .addComponent(btnAddSupplier, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEditSupplier, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnDeleteSupplier, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddSupplier, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(btnEditSupplier, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDeleteSupplier, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        cardContainer.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 980, 70));

        tblSuppliers.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Company Name", "Address", "Phone Number"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblSuppliers);

        cardContainer.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 940, 480));

        add(cardContainer, new java.awt.GridBagConstraints());
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddSupplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddSupplierActionPerformed
        java.awt.Window parentWindow = javax.swing.SwingUtilities.getWindowAncestor(this);
        java.awt.Frame parentFrame = (parentWindow instanceof java.awt.Frame) ? (java.awt.Frame) parentWindow : null;

        ui.dialogs.AddSupplierDialog dialog = new ui.dialogs.AddSupplierDialog(parentFrame, true);
        dialog.setLocationRelativeTo(parentFrame);
        dialog.setVisible(true);

        loadSuppliers("");
    }//GEN-LAST:event_btnAddSupplierActionPerformed

    private void btnEditSupplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditSupplierActionPerformed
        int selectedRow = tblSuppliers.getSelectedRow();

        if (selectedRow == -1) {
            javax.swing.JOptionPane.showMessageDialog(this, "Please select a supplier to edit.", "No Selection", javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }

        int supplierId = (int) tblSuppliers.getValueAt(selectedRow, 0);
        String name = (String) tblSuppliers.getValueAt(selectedRow, 1);
        String address = (String) tblSuppliers.getValueAt(selectedRow, 2);
        String phone = (String) tblSuppliers.getValueAt(selectedRow, 3);

        java.awt.Window parentWindow = javax.swing.SwingUtilities.getWindowAncestor(this);
        java.awt.Frame parentFrame = (parentWindow instanceof java.awt.Frame) ? (java.awt.Frame) parentWindow : null;

        ui.dialogs.EditSupplierDialog dialog = new ui.dialogs.EditSupplierDialog(parentFrame, true, supplierId, name, address, phone);
        dialog.setLocationRelativeTo(parentFrame);
        dialog.setVisible(true);

        loadSuppliers("");
    }//GEN-LAST:event_btnEditSupplierActionPerformed

    private void btnDeleteSupplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteSupplierActionPerformed
        int selectedRow = tblSuppliers.getSelectedRow();

        if (selectedRow == -1) {
            javax.swing.JOptionPane.showMessageDialog(this, "Please select a supplier to archive.", "No Selection", javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }

        int supplierId = (int) tblSuppliers.getValueAt(selectedRow, 0);
        String supplierName = (String) tblSuppliers.getValueAt(selectedRow, 1);

        int confirm = javax.swing.JOptionPane.showConfirmDialog(this, 
                "Are you sure you want to archive '" + supplierName + "'?", 
                "Confirm Archive", javax.swing.JOptionPane.YES_NO_OPTION, javax.swing.JOptionPane.WARNING_MESSAGE);

        if (confirm == javax.swing.JOptionPane.YES_OPTION) {
            try {
                java.sql.Connection conn = database.DBConnection.getConnection();
                
                String sql = "UPDATE Suppliers SET is_archived = 1 WHERE supplier_id = ?";
                java.sql.PreparedStatement pstmt = conn.prepareStatement(sql);
                pstmt.setInt(1, supplierId);
                pstmt.executeUpdate();
                
                String logSql = "INSERT INTO AuditLogs (user_id, action, description) VALUES (?, 'ARCHIVE_SUPPLIER', ?)";
                java.sql.PreparedStatement logStmt = conn.prepareStatement(logSql);
                logStmt.setInt(1, LoginPanel.loggedInUserId);
                logStmt.setString(2, "Archived supplier: " + supplierName);
                logStmt.executeUpdate();

                javax.swing.JOptionPane.showMessageDialog(this, "Supplier successfully archived.");
                loadSuppliers(""); 
                
            } catch (Exception e) {
                e.printStackTrace();
                javax.swing.JOptionPane.showMessageDialog(this, "Database Error: " + e.getMessage(), "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnDeleteSupplierActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddSupplier;
    private javax.swing.JButton btnDeleteSupplier;
    private javax.swing.JButton btnEditSupplier;
    private javax.swing.JPanel cardContainer;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblSuppliers;
    // End of variables declaration//GEN-END:variables
}
