package ui.menuPanel;

// Imports Swing constants for alignment
import javax.swing.SwingConstants;

// Imports table cell renderer
import javax.swing.table.DefaultTableCellRenderer;

// Imports LoginPanel to get logged-in user ID
import ui.auth.LoginPanel;

public class SuppliersPanel extends javax.swing.JPanel {

    // Constructor
    // Runs when SuppliersPanel is created
    public SuppliersPanel() {

        // Initializes all UI components
        initComponents();

        // Styles the table header font
        tblSuppliers.getTableHeader().setFont(
                new java.awt.Font(
                        "Geist SemiBold",
                        java.awt.Font.PLAIN,
                        10
                )
        );

        // Changes table header background color
        tblSuppliers.getTableHeader().setBackground(
                new java.awt.Color(245, 245, 245)
        );

        // Changes table header text color
        tblSuppliers.getTableHeader().setForeground(
                new java.awt.Color(80, 80, 80)
        );

        // Removes spacing between table cells
        tblSuppliers.setIntercellSpacing(
                new java.awt.Dimension(0, 0)
        );

        // Removes table grid lines
        tblSuppliers.setShowGrid(false);

        // Creates center alignment renderer
        DefaultTableCellRenderer centerRenderer
                = new DefaultTableCellRenderer();

        // Centers text horizontally
        centerRenderer.setHorizontalAlignment(
                SwingConstants.CENTER
        );

        // Applies center alignment to all columns
        for (int i = 0; i < tblSuppliers.getColumnCount(); i++) {

            tblSuppliers.getColumnModel()
                    .getColumn(i)
                    .setCellRenderer(centerRenderer);
        }

        // Loads supplier records into table
        loadSuppliers("");
    }

    // Loads supplier records from database
    public void loadSuppliers(String searchQuery) {

        // Checks if archived suppliers should be shown
        boolean showArchived
                = chkShowArchived.isSelected();

        // Determines archive flag value
        int archiveFlag
                = showArchived ? 1 : 0;

        // SQL query:
        // Gets suppliers based on archive status
        String sql
                = "SELECT supplier_id, "
                + "supplier_name, "
                + "contact_no, "
                + "address "
                + "FROM Suppliers "
                + "WHERE is_archived = ? "
                + "AND (supplier_name LIKE ? "
                + "OR address LIKE ?) "
                + "ORDER BY supplier_id DESC";

        try (
                // Connects to database
                java.sql.Connection conn
                = database.DBConnection.getConnection(); // Creates PreparedStatement
                 java.sql.PreparedStatement pstmt
                = conn.prepareStatement(sql)) {

            // Adds wildcard search filter
            String searchParam
                    = "%" + searchQuery.trim() + "%";

            // Inserts archive filter
            pstmt.setInt(1, archiveFlag);

            // Inserts search parameter
            pstmt.setString(2, searchParam);
            pstmt.setString(3, searchParam);

            try (
                    // Executes SELECT query
                    java.sql.ResultSet rs
                    = pstmt.executeQuery()) {

                // Gets table model
                javax.swing.table.DefaultTableModel model
                        = (javax.swing.table.DefaultTableModel) tblSuppliers.getModel();

                // Clears existing rows
                model.setRowCount(0);

                // Loops through supplier records
                while (rs.next()) {

                    // Adds row into table
                    model.addRow(new Object[]{
                        rs.getInt("supplier_id"),
                        rs.getString("supplier_name"),
                        rs.getString("address"),
                        rs.getString("contact_no")
                    });
                }
            }

        } catch (Exception e) {

            // Prints error in console
            e.printStackTrace();

            // Shows database/system error
            javax.swing.JOptionPane.showMessageDialog(
                    this,
                    "Error loading suppliers: "
                    + e.getMessage()
            );
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cardContainer = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnAddSupplier = new javax.swing.JButton();
        btnEditSupplier = new javax.swing.JButton();
        btnArchive = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblSuppliers = new javax.swing.JTable();
        chkShowArchived = new javax.swing.JCheckBox();

        setBackground(new java.awt.Color(248, 250, 252));
        setLayout(new java.awt.GridBagLayout());

        cardContainer.setBackground(new java.awt.Color(255, 255, 255));
        cardContainer.setMaximumSize(new java.awt.Dimension(980, 610));
        cardContainer.setMinimumSize(new java.awt.Dimension(980, 610));
        cardContainer.setPreferredSize(new java.awt.Dimension(980, 610));
        cardContainer.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(226, 232, 240)));

        jLabel1.setFont(new java.awt.Font("Georgia", 1, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(15, 23, 42));
        jLabel1.setText("Manage Suppliers");

        btnAddSupplier.setBackground(new java.awt.Color(227, 83, 10));
        btnAddSupplier.setFont(new java.awt.Font("Geist SemiBold", 0, 12)); // NOI18N
        btnAddSupplier.setForeground(new java.awt.Color(255, 255, 255));
        btnAddSupplier.setText("Add Supplier");
        btnAddSupplier.setPreferredSize(new java.awt.Dimension(100, 35));
        btnAddSupplier.addActionListener(this::btnAddSupplierActionPerformed);

        btnEditSupplier.setBackground(new java.awt.Color(241, 245, 249));
        btnEditSupplier.setFont(new java.awt.Font("Geist SemiBold", 0, 12)); // NOI18N
        btnEditSupplier.setText("Edit");
        btnEditSupplier.setPreferredSize(new java.awt.Dimension(100, 35));
        btnEditSupplier.addActionListener(this::btnEditSupplierActionPerformed);

        btnArchive.setBackground(new java.awt.Color(254, 226, 226));
        btnArchive.setFont(new java.awt.Font("Geist SemiBold", 0, 12)); // NOI18N
        btnArchive.setForeground(new java.awt.Color(153, 27, 27));
        btnArchive.setText("Archive");
        btnArchive.setPreferredSize(new java.awt.Dimension(100, 35));
        btnArchive.addActionListener(this::btnArchiveActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 478, Short.MAX_VALUE)
                .addComponent(btnAddSupplier, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEditSupplier, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnArchive, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddSupplier, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(btnEditSupplier, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnArchive, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        cardContainer.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 980, 70));

        tblSuppliers.setFont(new java.awt.Font("Geist", 0, 12)); // NOI18N
        tblSuppliers.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Company Name", "Address", "Phone Number"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblSuppliers.setRowHeight(35);
        jScrollPane1.setViewportView(tblSuppliers);

        cardContainer.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 940, 470));

        chkShowArchived.setFont(new java.awt.Font("Geist SemiBold", 0, 10)); // NOI18N
        chkShowArchived.setText("Show Archived");
        chkShowArchived.addActionListener(this::chkShowArchivedActionPerformed);
        cardContainer.add(chkShowArchived, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 100, -1));

        add(cardContainer, new java.awt.GridBagConstraints());
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddSupplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddSupplierActionPerformed
        // Gets current window
        java.awt.Window parentWindow
                = javax.swing.SwingUtilities
                        .getWindowAncestor(this);

        // Converts window into Frame
        java.awt.Frame parentFrame
                = (parentWindow instanceof java.awt.Frame)
                        ? (java.awt.Frame) parentWindow
                        : null;

        // Opens AddSupplierDialog
        ui.dialogs.AddSupplierDialog dialog
                = new ui.dialogs.AddSupplierDialog(
                        parentFrame,
                        true
                );

        // Centers dialog relative to parent frame
        dialog.setLocationRelativeTo(parentFrame);

        // Displays dialog
        dialog.setVisible(true);

        // Reloads updated supplier records
        loadSuppliers("");
    }//GEN-LAST:event_btnAddSupplierActionPerformed

    private void btnEditSupplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditSupplierActionPerformed
        // Gets selected row from table
        int selectedRow
                = tblSuppliers.getSelectedRow();

        // Validation:
        // Checks if user selected a row
        if (selectedRow == -1) {

            javax.swing.JOptionPane.showMessageDialog(
                    this,
                    "Please select a supplier to edit.",
                    "No Selection",
                    javax.swing.JOptionPane.WARNING_MESSAGE
            );

            return;
        }

        // Gets selected supplier information
        int supplierId
                = (int) tblSuppliers.getValueAt(
                        selectedRow,
                        0
                );

        String name
                = (String) tblSuppliers.getValueAt(
                        selectedRow,
                        1
                );

        String address
                = (String) tblSuppliers.getValueAt(
                        selectedRow,
                        2
                );

        String phone
                = (String) tblSuppliers.getValueAt(
                        selectedRow,
                        3
                );

        // Gets current window
        java.awt.Window parentWindow
                = javax.swing.SwingUtilities
                        .getWindowAncestor(this);

        // Converts window into Frame
        java.awt.Frame parentFrame
                = (parentWindow instanceof java.awt.Frame)
                        ? (java.awt.Frame) parentWindow
                        : null;

        // Opens EditSupplierDialog
        ui.dialogs.EditSupplierDialog dialog
                = new ui.dialogs.EditSupplierDialog(
                        parentFrame,
                        true,
                        supplierId,
                        name,
                        address,
                        phone
                );

        // Centers dialog relative to parent frame
        dialog.setLocationRelativeTo(parentFrame);

        // Displays dialog
        dialog.setVisible(true);

        // Reloads updated supplier records
        loadSuppliers("");
    }//GEN-LAST:event_btnEditSupplierActionPerformed

    private void btnArchiveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnArchiveActionPerformed
        // Gets selected row from table
        int selectedRow
                = tblSuppliers.getSelectedRow();

        // Validation:
        // Checks if user selected a row
        if (selectedRow == -1) {

            javax.swing.JOptionPane.showMessageDialog(
                    this,
                    "Please select a supplier first."
            );

            return;
        }

        // Gets selected supplier ID
        int supplierId
                = (int) tblSuppliers.getValueAt(
                        selectedRow,
                        0
                );

        // Gets selected supplier name
        String supplierName
                = (String) tblSuppliers.getValueAt(
                        selectedRow,
                        1
                );

        // Checks if currently viewing archived suppliers
        boolean isArchivedView
                = chkShowArchived.isSelected();

        // Determines action text
        String actionWord
                = isArchivedView
                        ? "restore"
                        : "archive";

        // Determines audit log action
        String logAction
                = isArchivedView
                        ? "RESTORE_SUPPLIER"
                        : "ARCHIVE_SUPPLIER";

        // Determines archive status value
        int newArchiveStatus
                = isArchivedView
                        ? 0
                        : 1;

        // Confirmation dialog
        int confirm
                = javax.swing.JOptionPane.showConfirmDialog(
                        this,
                        "Are you sure you want to "
                        + actionWord
                        + " '"
                        + supplierName
                        + "'?",
                        "Confirm Action",
                        javax.swing.JOptionPane.YES_NO_OPTION
                );

        // Runs if user clicks YES
        if (confirm
                == javax.swing.JOptionPane.YES_OPTION) {

            try (
                    // Connects to database
                    java.sql.Connection conn
                    = database.DBConnection.getConnection()) {

                // ================= SUPPLIER ARCHIVE UPDATE =================
                // SQL query:
                // Updates archive status
                String sql
                        = "UPDATE Suppliers "
                        + "SET is_archived = ? "
                        + "WHERE supplier_id = ?";

                try (
                        // Creates PreparedStatement
                        java.sql.PreparedStatement pstmt
                        = conn.prepareStatement(sql)) {

                    // Updates archive status
                    pstmt.setInt(1, newArchiveStatus);

                    // Selects correct supplier
                    pstmt.setInt(2, supplierId);

                    // Executes UPDATE query
                    pstmt.executeUpdate();
                }

                // ================= AUDIT LOG =================
                // SQL query:
                // Calls stored procedure for audit logs
                String logSql
                        = "{call sp_InsertAuditLog(?, ?, ?)}";

                try (
                        // Creates CallableStatement
                        java.sql.CallableStatement cstmtLog
                        = conn.prepareCall(logSql)) {

                    // Inserts logged-in user ID
                    cstmtLog.setInt(
                            1,
                            LoginPanel.loggedInUserId
                    );

                    // Inserts action type
                    cstmtLog.setString(
                            2,
                            logAction
                    );

                    // Inserts audit description
                    cstmtLog.setString(
                            3,
                            actionWord.substring(0, 1)
                                    .toUpperCase()
                            + actionWord.substring(1)
                            + "d Supplier ID: "
                            + supplierId
                    );

                    // Executes stored procedure
                    cstmtLog.execute();
                }

                // Success message
                javax.swing.JOptionPane.showMessageDialog(
                        this,
                        "Supplier "
                        + actionWord
                        + "d successfully."
                );

                // Reloads updated supplier records
                loadSuppliers("");

            } catch (Exception e) {

                // Prints error in console
                e.printStackTrace();

                // Shows database/system error
                javax.swing.JOptionPane.showMessageDialog(
                        this,
                        "Error processing request: "
                        + e.getMessage()
                );
            }
        }
    }//GEN-LAST:event_btnArchiveActionPerformed

    private void chkShowArchivedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkShowArchivedActionPerformed
        // Changes button text based on checkbox state
        if (chkShowArchived.isSelected()) {

            btnArchive.setText("Restore");

        } else {

            btnArchive.setText("Archive");
        }

        // Reloads suppliers based on selected view
        loadSuppliers("");
    }//GEN-LAST:event_chkShowArchivedActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddSupplier;
    private javax.swing.JButton btnArchive;
    private javax.swing.JButton btnEditSupplier;
    private javax.swing.JPanel cardContainer;
    private javax.swing.JCheckBox chkShowArchived;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblSuppliers;
    // End of variables declaration//GEN-END:variables
}
