package ui.menuPanel;

import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;

public class SystemLogsPanel extends javax.swing.JPanel {

    public SystemLogsPanel() {
        initComponents();

        txtSearchLogs.putClientProperty("JTextField.placeholderText", "Search by action, user, or details...");
        tblLogs.getTableHeader().setFont(new java.awt.Font("Geist SemiBold", java.awt.Font.PLAIN, 12));
        tblLogs.getTableHeader().setBackground(new java.awt.Color(245, 245, 245));
        tblLogs.getTableHeader().setForeground(new java.awt.Color(80, 80, 80));
        tblLogs.setIntercellSpacing(new java.awt.Dimension(0, 0));
        tblLogs.setShowGrid(false);

        DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
        centerRenderer.setHorizontalAlignment(SwingConstants.CENTER);

        for (int i = 0; i < tblLogs.getColumnCount(); i++) {
            tblLogs.getColumnModel().getColumn(i).setCellRenderer(centerRenderer);
        }

        txtSearchLogs.getDocument().addDocumentListener(new javax.swing.event.DocumentListener() {
            public void changedUpdate(javax.swing.event.DocumentEvent e) {
                loadLogs(txtSearchLogs.getText());
            }

            public void removeUpdate(javax.swing.event.DocumentEvent e) {
                loadLogs(txtSearchLogs.getText());
            }

            public void insertUpdate(javax.swing.event.DocumentEvent e) {
                loadLogs(txtSearchLogs.getText());
            }
        });

        loadLogs("");
    }

    public void loadLogs(String searchQuery) {
        try {
            java.sql.Connection conn = database.DBConnection.getConnection();

            String sql = "SELECT a.log_id, a.log_date, ISNULL(u.username, 'System') AS username, a.action, a.description "
                    + "FROM AuditLogs a "
                    + "LEFT JOIN Users u ON a.user_id = u.user_id "
                    + "WHERE a.action LIKE ? OR a.description LIKE ? OR ISNULL(u.username, '') LIKE ? "
                    + "ORDER BY a.log_date DESC";

            java.sql.PreparedStatement pstmt = conn.prepareStatement(sql);
            String searchParam = "%" + searchQuery.trim() + "%";
            pstmt.setString(1, searchParam);
            pstmt.setString(2, searchParam);
            pstmt.setString(3, searchParam);

            java.sql.ResultSet rs = pstmt.executeQuery();
            javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) tblLogs.getModel();
            model.setRowCount(0);

            java.text.SimpleDateFormat sdf = new java.text.SimpleDateFormat("MMM dd, yyyy - hh:mm a");

            while (rs.next()) {
                model.addRow(new Object[]{
                    rs.getInt("log_id"),
                    sdf.format(rs.getTimestamp("log_date")),
                    rs.getString("username"),
                    rs.getString("action"),
                    rs.getString("description") != null ? rs.getString("description") : ""
                });
            }
        } catch (Exception e) {
            e.printStackTrace();
            javax.swing.JOptionPane.showMessageDialog(this, "Error loading system logs: " + e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtSearchLogs = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblLogs = new javax.swing.JTable();

        setBackground(new java.awt.Color(248, 250, 252));
        setLayout(new java.awt.GridBagLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setMaximumSize(new java.awt.Dimension(980, 610));
        jPanel1.setMinimumSize(new java.awt.Dimension(980, 610));
        jPanel1.setPreferredSize(new java.awt.Dimension(980, 610));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(226, 232, 240)));

        jLabel1.setFont(new java.awt.Font("Georgia", 1, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(15, 23, 42));
        jLabel1.setText("System Activity Logs");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1)
                .addContainerGap(753, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(20, 20, 20))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        txtSearchLogs.setFont(new java.awt.Font("Geist", 0, 12)); // NOI18N
        txtSearchLogs.addActionListener(this::txtSearchLogsActionPerformed);
        jPanel1.add(txtSearchLogs, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 250, 30));

        btnSearch.setFont(new java.awt.Font("Geist SemiBold", 0, 12)); // NOI18N
        btnSearch.setText("Search");
        btnSearch.addActionListener(this::btnSearchActionPerformed);
        jPanel1.add(btnSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 90, 100, 30));

        tblLogs.setFont(new java.awt.Font("Geist", 0, 12)); // NOI18N
        tblLogs.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Log ID", "Timestamp", "User", "Action", "Details"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblLogs.setRowHeight(35);
        jScrollPane1.setViewportView(tblLogs);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 920, 450));

        add(jPanel1, new java.awt.GridBagConstraints());
    }// </editor-fold>//GEN-END:initComponents

    private void txtSearchLogsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchLogsActionPerformed
        loadLogs(txtSearchLogs.getText()); // Trigger search when they hit Enter
    }//GEN-LAST:event_txtSearchLogsActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        loadLogs(txtSearchLogs.getText());
    }//GEN-LAST:event_btnSearchActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSearch;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblLogs;
    private javax.swing.JTextField txtSearchLogs;
    // End of variables declaration//GEN-END:variables
}
