package ui.menuPanel;

import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import ui.auth.LoginPanel;

public class TransactionsPanel extends javax.swing.JPanel {

    public TransactionsPanel() {
        initComponents();
        
        txtSearchLogs.putClientProperty("JTextField.placeholderText", "Search by Receipt ID or Cashier Name");

        tblTransactions.getTableHeader().setFont(
                new java.awt.Font("Geist SemiBold", java.awt.Font.PLAIN, 10)
        );
        tblTransactions.getTableHeader().setBackground(
                new java.awt.Color(245, 245, 245)
        );
        tblTransactions.getTableHeader().setForeground(
                new java.awt.Color(80, 80, 80)
        );
        tblTransactions.setIntercellSpacing(new java.awt.Dimension(0, 0));
        tblTransactions.setShowGrid(false);
        
        DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
        centerRenderer.setHorizontalAlignment(SwingConstants.CENTER);

        for (int i = 0; i < tblTransactions.getColumnCount(); i++) {
            tblTransactions.getColumnModel().getColumn(i).setCellRenderer(centerRenderer);
        }

        txtSearchLogs.getDocument().addDocumentListener(new javax.swing.event.DocumentListener() {
            public void changedUpdate(javax.swing.event.DocumentEvent e) {
                loadTransactions(txtSearchLogs.getText());
            }

            public void removeUpdate(javax.swing.event.DocumentEvent e) {
                loadTransactions(txtSearchLogs.getText());
            }

            public void insertUpdate(javax.swing.event.DocumentEvent e) {
                loadTransactions(txtSearchLogs.getText());
            }
        });

        loadTransactions("");
    }

    public void loadTransactions(String searchQuery) {
        String sql = "SELECT t.transaction_id, t.transaction_date, u.username, t.total_amount, t.status "
                   + "FROM Transactions t "
                   + "INNER JOIN Users u ON t.user_id = u.user_id "
                   + "WHERE u.username LIKE ? OR CAST(t.transaction_id AS VARCHAR) LIKE ? "
                   + "ORDER BY t.transaction_date DESC";

       
        try (java.sql.Connection conn = database.DBConnection.getConnection();
             java.sql.PreparedStatement pstmt = conn.prepareStatement(sql)) {
             
            String searchParam = "%" + searchQuery.trim() + "%";
            pstmt.setString(1, searchParam);
            pstmt.setString(2, searchParam);

            try (java.sql.ResultSet rs = pstmt.executeQuery()) {
                javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) tblTransactions.getModel();
                model.setRowCount(0); 

                java.text.SimpleDateFormat sdf = new java.text.SimpleDateFormat("MMM dd, yyyy - hh:mm a");

                while (rs.next()) {
                    model.addRow(new Object[]{
                        rs.getInt("transaction_id"),
                        sdf.format(rs.getTimestamp("transaction_date")),
                        rs.getString("username"),
                        rs.getDouble("total_amount"),
                        rs.getString("status")
                    });
                }
            }
        } catch (Exception e) {
            e.printStackTrace();
            javax.swing.JOptionPane.showMessageDialog(this, "Error loading transactions: " + e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cardContainer = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnViewDetails = new javax.swing.JButton();
        btnVoidSale = new javax.swing.JButton();
        txtSearchLogs = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblTransactions = new javax.swing.JTable();

        setBackground(new java.awt.Color(248, 250, 252));
        setLayout(new java.awt.GridBagLayout());

        cardContainer.setBackground(new java.awt.Color(255, 255, 255));
        cardContainer.setMaximumSize(new java.awt.Dimension(980, 610));
        cardContainer.setMinimumSize(new java.awt.Dimension(980, 610));
        cardContainer.setPreferredSize(new java.awt.Dimension(980, 610));
        cardContainer.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(226, 232, 240)));
        jPanel2.setPreferredSize(new java.awt.Dimension(980, 70));

        jLabel1.setFont(new java.awt.Font("Georgia", 1, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(15, 23, 42));
        jLabel1.setText("Sales History");

        btnViewDetails.setBackground(new java.awt.Color(231, 90, 14));
        btnViewDetails.setFont(new java.awt.Font("Geist SemiBold", 0, 12)); // NOI18N
        btnViewDetails.setForeground(new java.awt.Color(255, 255, 255));
        btnViewDetails.setText("View Details");
        btnViewDetails.setPreferredSize(new java.awt.Dimension(113, 30));
        btnViewDetails.addActionListener(this::btnViewDetailsActionPerformed);

        btnVoidSale.setBackground(new java.awt.Color(254, 226, 226));
        btnVoidSale.setFont(new java.awt.Font("Geist SemiBold", 0, 12)); // NOI18N
        btnVoidSale.setForeground(new java.awt.Color(153, 27, 27));
        btnVoidSale.setText("Void");
        btnVoidSale.setPreferredSize(new java.awt.Dimension(113, 30));
        btnVoidSale.addActionListener(this::btnVoidSaleActionPerformed);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 620, Short.MAX_VALUE)
                .addComponent(btnViewDetails, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnVoidSale, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnViewDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnVoidSale, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(13, 13, 13))
        );

        cardContainer.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 980, -1));

        txtSearchLogs.setFont(new java.awt.Font("Geist", 0, 12)); // NOI18N
        txtSearchLogs.setToolTipText("Search by Receipt ID or Cashier Name");
        txtSearchLogs.addActionListener(this::txtSearchLogsActionPerformed);
        cardContainer.add(txtSearchLogs, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 260, 30));

        btnSearch.setFont(new java.awt.Font("Geist SemiBold", 0, 12)); // NOI18N
        btnSearch.setText("Search");
        btnSearch.addActionListener(this::btnSearchActionPerformed);
        cardContainer.add(btnSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 90, 100, 30));

        tblTransactions.setFont(new java.awt.Font("Geist", 0, 12)); // NOI18N
        tblTransactions.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Receipt ID", "Date & Time", "Cashier", "Total Amount", "Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblTransactions.setRowHeight(35);
        jScrollPane1.setViewportView(tblTransactions);

        cardContainer.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 940, 460));

        add(cardContainer, new java.awt.GridBagConstraints());
    }// </editor-fold>//GEN-END:initComponents

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSearchActionPerformed

    private void btnViewDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewDetailsActionPerformed
        int selectedRow = tblTransactions.getSelectedRow();

        if (selectedRow == -1) {
            javax.swing.JOptionPane.showMessageDialog(this, "Please select a transaction to view.", "No Selection", javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }

        int transactionId = (int) tblTransactions.getValueAt(selectedRow, 0);

        try {
            java.sql.Connection conn = database.DBConnection.getConnection();

            String sqlHeader = "SELECT u.username, t.total_amount, t.cash_tendered, t.transaction_date "
                    + "FROM Transactions t INNER JOIN Users u ON t.user_id = u.user_id "
                    + "WHERE t.transaction_id = ?";
            java.sql.PreparedStatement pstmtHeader = conn.prepareStatement(sqlHeader);
            pstmtHeader.setInt(1, transactionId);
            java.sql.ResultSet rsHeader = pstmtHeader.executeQuery();

            String cashierName = "Unknown";
            double totalAmount = 0.0;
            double cashReceived = 0.0;
            String date = "";

            if (rsHeader.next()) {
                cashierName = rsHeader.getString("username");
                totalAmount = rsHeader.getDouble("total_amount");
                cashReceived = rsHeader.getDouble("cash_tendered");
                date = new java.text.SimpleDateFormat("MMM dd, yyyy hh:mm a").format(rsHeader.getTimestamp("transaction_date"));
            }

            double change = cashReceived - totalAmount;
            double vatableSales = totalAmount / 1.12;
            double vatAmount = totalAmount - vatableSales;

            StringBuilder receipt = new StringBuilder();
            receipt.append("==========================================\n");
            receipt.append("              WEEFEE FOODHUB\n");
            receipt.append("        1878 Tayuman St. Sta. Cruz\n");
            receipt.append("              Manila Philippines\n");
            receipt.append("------------------------------------------\n");
            receipt.append("              SALES INVOICE\n");
            receipt.append("TIN: 123-456-789-000\n");
            receipt.append("VAT REG TIN\n");
            receipt.append("MIN: 24010123456789012\n");
            receipt.append("==========================================\n");
            receipt.append(String.format("Receipt No : %d\n", transactionId));
            receipt.append(String.format("Date       : %s\n", date));
            receipt.append(String.format("Cashier    : %s\n", cashierName));
            receipt.append("------------------------------------------\n");
            receipt.append(String.format("%-22s %-5s %11s\n", "ITEM", "QTY", "TOTAL"));
            receipt.append("------------------------------------------\n");

            String sqlItems = "SELECT p.name, td.quantity, td.selling_price, (td.quantity * td.selling_price) AS subtotal "
                    + "FROM Transaction_Details td "
                    + "INNER JOIN Products p ON td.product_id = p.product_id "
                    + "WHERE td.transaction_id = ?";
            java.sql.PreparedStatement pstmtItems = conn.prepareStatement(sqlItems);
            pstmtItems.setInt(1, transactionId);
            java.sql.ResultSet rsItems = pstmtItems.executeQuery();

            while (rsItems.next()) {
                String rawName = rsItems.getString("name");
                String itemName = rawName.length() > 18 ? rawName.substring(0, 18) : rawName;
                int qty = rsItems.getInt("quantity");
                double subtotal = rsItems.getDouble("subtotal");

                receipt.append(String.format("%-22s %-5d   ₱%8.2f\n", itemName, qty, subtotal));
            }

            receipt.append("------------------------------------------\n");
            receipt.append(String.format("%-25s ₱%11.2f\n", "VATable Sales", vatableSales));
            receipt.append(String.format("%-25s ₱%11.2f\n", "VAT Amount", vatAmount));
            receipt.append(String.format("%-25s ₱%11.2f\n", "TOTAL", totalAmount));
            receipt.append(String.format("%-25s ₱%11.2f\n", "CASH", cashReceived));
            receipt.append(String.format("%-25s ₱%11.2f\n", "CHANGE", change));
            receipt.append("==========================================\n");
            receipt.append("      THIS SERVES AS YOUR SALES INVOICE   \n");
            receipt.append("            THANK YOU! COME AGAIN         \n");
            receipt.append("==========================================\n");

            javax.swing.JTextArea txtReceipt = new javax.swing.JTextArea(receipt.toString());
            txtReceipt.setFont(new java.awt.Font("Monospaced", java.awt.Font.BOLD, 14)); 
            txtReceipt.setEditable(false);
            txtReceipt.setBackground(new java.awt.Color(255, 255, 255));
            txtReceipt.setForeground(new java.awt.Color(15, 23, 42));
            txtReceipt.setMargin(new java.awt.Insets(20, 20, 20, 20)); 

            javax.swing.JScrollPane scrollPane = new javax.swing.JScrollPane(txtReceipt);
            scrollPane.setPreferredSize(new java.awt.Dimension(400, 500));
            scrollPane.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(226, 232, 240)));

        
            javax.swing.JOptionPane.showMessageDialog(this, scrollPane, "Digital Receipt", javax.swing.JOptionPane.PLAIN_MESSAGE);

        } catch (Exception e) {
            e.printStackTrace();
            javax.swing.JOptionPane.showMessageDialog(this, "Error loading receipt details: " + e.getMessage(), "Database Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnViewDetailsActionPerformed

    private void btnVoidSaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoidSaleActionPerformed
        int selectedRow = tblTransactions.getSelectedRow();

        if (selectedRow == -1) {
            javax.swing.JOptionPane.showMessageDialog(this, "Please select a transaction to void.", "No Selection", javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }

        int transactionId = (int) tblTransactions.getValueAt(selectedRow, 0);
        String currentStatus = (String) tblTransactions.getValueAt(selectedRow, 4); // Column 4 is Status

        if ("VOIDED".equalsIgnoreCase(currentStatus)) {
            javax.swing.JOptionPane.showMessageDialog(this, "This transaction has already been voided.", "Already Voided", javax.swing.JOptionPane.INFORMATION_MESSAGE);
            return;
        }

        int confirm = javax.swing.JOptionPane.showConfirmDialog(this,
                "Are you sure you want to VOID Receipt #" + transactionId + "?\nThis will restore the items to inventory.",
                "Confirm Void", javax.swing.JOptionPane.YES_NO_OPTION, javax.swing.JOptionPane.WARNING_MESSAGE);

        if (confirm != javax.swing.JOptionPane.YES_OPTION) {
            return;
        }

        java.sql.Connection conn = null;
        try {
            conn = database.DBConnection.getConnection();
            conn.setAutoCommit(false); 

            String sqlVoid = "UPDATE Transactions SET status = 'VOIDED' WHERE transaction_id = ?";
            try (java.sql.PreparedStatement pstmtVoid = conn.prepareStatement(sqlVoid)) {
                pstmtVoid.setInt(1, transactionId);
                pstmtVoid.executeUpdate();
            }

            String sqlGetItems = "SELECT product_id, quantity FROM Transaction_Details WHERE transaction_id = ?";
            String sqlRestore = "UPDATE Inventory SET current_stock = current_stock + ? WHERE product_id = ?";
            
            try (java.sql.PreparedStatement pstmtGetItems = conn.prepareStatement(sqlGetItems);
                 java.sql.PreparedStatement pstmtRestore = conn.prepareStatement(sqlRestore)) {
                 
                pstmtGetItems.setInt(1, transactionId);
                try (java.sql.ResultSet rsItems = pstmtGetItems.executeQuery()) {
                    while (rsItems.next()) {
                        int productId = rsItems.getInt("product_id");
                        int qtyToReturn = rsItems.getInt("quantity");

                        pstmtRestore.setInt(1, qtyToReturn);
                        pstmtRestore.setInt(2, productId);
                        pstmtRestore.addBatch(); 
                    }
                }
                pstmtRestore.executeBatch(); 
            }

            String sqlLog = "{call sp_InsertAuditLog(?, ?, ?)}";
            try (java.sql.CallableStatement cstmtLog = conn.prepareCall(sqlLog)) {
                cstmtLog.setInt(1, LoginPanel.loggedInUserId); 
                cstmtLog.setString(2, "VOID_SALE"); 
                cstmtLog.setString(3, "Voided Transaction ID: " + transactionId + " and restored inventory.");
                cstmtLog.execute(); 
            }

            conn.commit();

            javax.swing.JOptionPane.showMessageDialog(this, "Transaction #" + transactionId + " successfully voided.\nInventory has been restored.", "Void Successful", javax.swing.JOptionPane.INFORMATION_MESSAGE);

            loadTransactions(txtSearchLogs.getText());

        } catch (Exception e) {
            try { if (conn != null) conn.rollback(); } catch (Exception ex) {} 
            e.printStackTrace();
            javax.swing.JOptionPane.showMessageDialog(this, "Error voiding transaction: " + e.getMessage(), "Database Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        } finally {
            if (conn != null) {
                try { conn.setAutoCommit(true); } catch (Exception ex) {} 
                try { conn.close(); } catch (Exception ex) {} 
            }
        }
    }//GEN-LAST:event_btnVoidSaleActionPerformed

    private void txtSearchLogsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchLogsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSearchLogsActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnViewDetails;
    private javax.swing.JButton btnVoidSale;
    private javax.swing.JPanel cardContainer;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblTransactions;
    private javax.swing.JTextField txtSearchLogs;
    // End of variables declaration//GEN-END:variables
}
